LPPlatform={};
(function(){LPPlatform.openAcctsIframe=function(a,b){var c=-1!==document.location.href.indexOf("vault.php");a.webvault=c?"1":"0";var d=LPTools.createElement("iframe","acctsiframe");d.src=c?"iframe.php":"iframe.html";LPPlatform.addEventListener(d,"load",function(){d.contentWindow.goTo(LPProxy.getBaseURL()+"acctsiframe.php?"+$.param(a),b);LPTools.addClass(d,"loaded")});document.body.appendChild(d);bg.onSettingsIframeClose(function(){try{document.body.removeChild(d)}catch(e){LPPlatform.logException(e)}})};LPPlatform.shouldShowVaultLoginButton=
function(){return!0};LPPlatform.lpIsExtension=function(){return!0};LPPlatform.openURL=function(a){bg.openURL(a)};LPPlatform.getBaseURL=function(){return bg.get("base_url")};LPPlatform.doAjax=function(a){$.ajax(a)};LPPlatform.ajax=function(a){bg.isOffline()?a.error&&a.error(null,null,"offline"):LPPlatform.doAjax(a)};LPPlatform.getOpenGroups=function(){var a=bg.localStorage_getItem(bg.db_prepend(bg.get("g_username_hash")+".savedtree"));if(null!==a){var b={};a=LPProxy.decrypt(a).split(",");for(var c=
0,d=a.length;c<d;++c){var e=a[c];0===e.indexOf("_")&&(e=e.substring(1));b[e]=!0}return b}return null};LPPlatform.setOpenGroups=function(a){for(var b=0,c=a.length;b<c;++b)a[b]="_"+a[b];a=LPProxy.encrypt(a.join(","));bg.localStorage_setItem(bg.db_prepend(bg.get("g_username_hash")+".savedtree"),a)};LPPlatform.initialized=function(){return!0};LPPlatform.getHTML=function(a,b){$.ajax({url:a,success:b,dataType:"text"})};LPPlatform.purchasePremium=function(){window.open(LPProxy.getBaseURL()+"features_joinpremium4.php?a=1",
"_blank")};LPPlatform.loadedPreferences=function(){return LPTools.hasProperties(bg.get("g_userprefs"))};LPPlatform.openAttachment=function(a){bg.openAttach(a._parentNote.getID(),a.getID())};LPPlatform.saveAttachment=function(a){bg.exportAttachment(a._parentNote.getID(),a.getID())};LPPlatform.logException=function(a){var b="string"===typeof a?a:a.message;a.stack&&(b+="\n"+a.stack);self.Raven&&self.Raven.captureException(a);LPPlatform.logError(b)};LPPlatform.logError=function(a){a="Page: "+window.location.href+
" Error: "+a;try{console.error(a),bg.lpReportError("VAULT_4_0: "+a)}catch(b){}};LPPlatform.addEventListener=function(a){if(a){for(var b=[],c=1;c<arguments.length;++c)b.push(arguments[c]);a.addEventListener.apply(a,b)}};LPPlatform.removeEventListener=function(a){for(var b=[],c=1;c<arguments.length;++c)b.push(arguments[c]);a.removeEventListener.apply(a,b)};LPPlatform.canBackgroundOpenPopover=function(){return!0};LPPlatform.generateSharingKeys=function(a){bg.generateSharingKeys(a)};LPPlatform.getResourcePath=
function(a){return a};LPPlatform.canPreventBlur=function(){return!0};LPPlatform.getBackgroundData=function(a){return a};LPPlatform.showIntroTutorial=function(){LPPlatform.openTour()};LPPlatform.setIntroTutorialDisable=function(a){return!1};LPPlatform.supportsBinary=function(){return!0};LPPlatform.openKeyboard=function(){bg.LPPlatform.openTabDialog("login",{virtualKeyboard:!0})};LPPlatform.getImportHandler=function(){return"importerHandler"};LPPlatform.showDownloader=function(){return!1};LPPlatform.openTour=
function(a,b){LPRequire.requireJS("lpPing lpTag Tour/lpPingManager Tour/lpTagManager Tour/introTourShade Tour/introTourPreferences Tour/FamilyOnboarding/familyOnboardingTour Tour/OmarMigrationTour/omarMigrationTour Tour/OmarVaultTour/omarVaultTour Tour/Vault41Tour/vault41Tour Tour/introTourData Tour/introTourFlow Tour/introTourQueue Tour/introTour".split(" "),function(){IntroTour&&IntroTour.start(a,b)})};LPPlatform.showSecondaryOnboarding=function(){LPRequire.requireJS(["SecondaryOnboarding/SecondaryOnboarding"],
function(){SecondaryOnboardingManager&&(new SecondaryOnboardingManager).init()})};LPPlatform.allowClipboardCopy=function(){return LPFeatures.allowClipboardCopy()};LPPlatform.getVersion=function(){return bg.get("lpversion")};LPPlatform.installBinary=function(a,b){bg.install_binary(a,b)};LPPlatform.requestNativeMessaging=function(a){bg.request_native_messaging(a)}})();
//# sourceMappingURL=newvault_platform_js.js.map