VaultLicenseExpiration=function(){var b,f,c,a,h,d=function(a){return void 0!==a&&7>=a&&1<=a},g=function(a,e,c,b){k(b);dialogs.vaultInfoBanner.open({title:Strings.translateString(a,e),dialogClass:"banner",segmentEvents:{show:{name:"license_expiration_seen"},upgrade:{name:"license_expiration_upgrade"},learn:{name:"license_expiration_learn_more"},close:{name:"license_expiration_dismiss"}},buttons:[{style:"btn-link",sizeStyle:"col-1 btn-container-sm",text:Strings.translateString("Learn More"),action:function(){bg.openPricingPage()},
closeOnClick:!0,segment:"learn"},{style:"btn-gray",sizeStyle:"col-2 btn-container-lg",text:Strings.translateString("Upgrade"),action:function(){c()},closeOnClick:!0,segment:"upgrade"}]})},k=function(a){var e=JSON.parse(sessionStorage.getItem("expirationData"));null===e&&(e={});e[a]=1;sessionStorage.setItem("expirationData",JSON.stringify(e))},l=function(a,e,c){var b=JSON.parse(a.getItem(e));if(null===b)return!1;var d=!1;c.forEach(function(a){d=d||b[a]});return d};return{initialize:function(){b=LPProxy.getAccountClass();
if(b===Constants.USER_PREMIUM_TRIAL||b===Constants.USER_FREE)f="number"===typeof bg.get("g_premium_trial_exp_days")?bg.get("g_premium_trial_exp_days"):void 0},setLicenseStatus:function(b,e,d){c=b;a=e;h=d},removeStoredLocalStoreExpPrefs:function(a){360<a&&null!==JSON.parse(localStorage.getItem("expiredData"))&&localStorage.removeItem("expiredData")},showExpirationMessage:function(){switch(b){case Constants.USER_ENTERPRISE_ADMIN:void 0!==a&&1>a?(k("dismissedEnterpriseExpired"),"trial"===c?dialogs.vaultTierExpiredDialog.open({dialogId:"EnterpriseTrialExpired",
paymentPage:bg.openEnterprisePaymentPage,storageItem:"dismissedEnterpriseExpired"}):dialogs.vaultTierExpiredDialog.open({dialogId:"EnterpriseLicenseExpired",paymentPage:bg.openEnterprisePaymentPage,storageItem:"dismissedEnterpriseExpired"})):"normal"===c&&d(a)&&1!==h?g("Your LastPass Enterprise license expires in %1 days.",a,bg.openEnterprisePaymentPage,"dismissedEnterpriseExpiring"):"trial"===c&&d(a)&&g("Your LastPass Enterprise trial expires in %1 days.",a,bg.openEnterprisePaymentPage,"dismissedEnterpriseExpiring");
break;case Constants.USER_TEAMS_ADMIN:void 0!==a&&1>a?(k("dismissedTeamsExpired"),"trial"===c?dialogs.vaultTierExpiredDialog.open({dialogId:"TeamsTrialExpired",paymentPage:bg.openTeamsPaymentPage,storageItem:"dismissedTeamsExpired"}):dialogs.vaultTierExpiredDialog.open({dialogId:"TeamsLicenseExpired",paymentPage:bg.openTeamsPaymentPage,storageItem:"dismissedTeamsExpired"})):"normal"===c&&d(a)&&1!==h?g("Your LastPass Teams license expires in %1 days.",a,bg.openTeamsPaymentPage,"dismissedTeamsExpiring"):
"trial"===c&&d(a)&&g("Your LastPass Teams trial expires in %1 days.",a,bg.openTeamsPaymentPage,"dismissedTeamsExpiring");break;case Constants.USER_FAMILY_ADMIN:void 0!==a&&1>a?(k("dismissedFamiliesExpired"),"trial"===c?dialogs.vaultTierExpiredDialog.open({dialogId:"FamiliesTrialExpired",paymentPage:bg.openFamiliesPaymentPage,storageItem:"dismissedFamiliesExpired"}):dialogs.vaultTierExpiredDialog.open({dialogId:"FamiliesLicenseExpired",paymentPage:bg.openFamiliesPaymentPage,storageItem:"dismissedFamiliesExpired"})):
"normal"===c&&d(a)&&1!==h?g("Your LastPass Families license expires in %1 days.",a,bg.openFamiliesPaymentPage,"dismissedFamiliesExpiring"):"trial"===c&&d(a)&&g("Your LastPass Families trial expires in %1 days.",a,bg.openFamiliesPaymentPage,"dismissedFamiliesExpiring");break;case Constants.USER_PREMIUM_TRIAL:d(f)&&g("Your LastPass Premium trial expires in %1 days.",f,bg.openPremiumPaymentPage,"dismissedPremiumTrialExpiring");break;case Constants.USER_FREE:void 0!==_premiumTrialExpirationDays&&1>_premiumTrialExpirationDays&&
-31<_premiumTrialExpirationDays&&dialogs.vaultTierExpiredDialog.open({dialogId:"PremiumTrialExpired",paymentPage:bg.openPremiumPaymentPage,storageItem:"dismissedPremiumTrialExpired"})}},premiumTrialStatusChecker:function(){return b===Constants.USER_PREMIUM_TRIAL&&d(f)&&!l(sessionStorage,"expirationData",["dismissedPremiumTrialExpiring"])||b===Constants.USER_FREE&&void 0!==f&&1>f&&-31<f&&!l(localStorage,"expiredData",["dismissedPremiumTrialExpired"])},companyLicenseStatusChecker:function(){var a=b===
Constants.USER_FAMILY_ADMIN||b===Constants.USER_ENTERPRISE_ADMIN||b===Constants.USER_TEAMS_ADMIN;a&&bg.BackgroundServer.licensing.getCompanyLicensing(function(a){!1!==a.success||VaultLicenseExpiration.hasDismissedEnterpriseExpiredNotification()?a.hasOwnProperty("daysleft")&&!VaultLicenseExpiration.hasDismissedEnterpriseExpiringNotification()?(VaultLicenseExpiration.removeStoredLocalStoreExpPrefs(a.daysleft),VaultLicenseExpiration.setLicenseStatus("normal",a.daysleft,a.hasOwnProperty("renewalstatus")?
a.renewalstatus:-1),VaultLicenseExpiration.showExpirationMessage()):a.hasOwnProperty("trialdaysleft")&&!VaultLicenseExpiration.hasDismissedEnterpriseExpiringNotification()&&(VaultLicenseExpiration.setLicenseStatus("trial",a.trialdaysleft,-1),VaultLicenseExpiration.showExpirationMessage()):(VaultLicenseExpiration.setLicenseStatus("TrialExpired"===a.code?"trial":"normal",0,-1),VaultLicenseExpiration.showExpirationMessage())});return a},hasDismissedEnterpriseExpiringNotification:function(){return l(sessionStorage,
"expirationData",["dismissedEnterpriseExpiring","dismissedTeamsExpiring","dismissedFamiliesExpiring"])},hasDismissedEnterpriseExpiredNotification:function(){return l(localStorage,"expiredData",["dismissedEnterpriseExpired","dismissedTeamsExpired","dismissedFamiliesExpired"])}}}();
//# sourceMappingURL=newvault_vaultLicenseExpiration_js.js.map