"undefined"!==typeof LPPlatform&&LPPlatform.addEventListener(document,"keydown",function(a){try{switch(a.keyCode||a.which){case 13:"checkbox"!==a.target.type?Topics.get(Topics.ENTER).publish(a):a.target.checked=!a.target.checked;break;case 27:Topics.get(Topics.ESCAPE).publish(a);break;case 37:Topics.get(Topics.LEFT_ARROW).publish(a);break;case 38:Topics.get(Topics.UP_ARROW).publish(a);break;case 39:Topics.get(Topics.RIGHT_ARROW).publish(a);break;case 40:Topics.get(Topics.DOWN_ARROW).publish(a)}}catch(e){LPPlatform.logException(e)}});
LPTools={};
(function(a){var e=[];a.setDragItems=function(a){e=a};a.getDragItems=function(){return e};a.buildItemButton=function(c){var b=Constants.ACTION_BUTTONS[c];return a.createElement("button",{"class":"itemButton "+b.css,vaultaction:c,title:Strings.Vault[b.title],allowmultiple:!1})};a.setupMiddleEllipsis=function(a){var b=a.find(".textOverflowContainer"),c=Math.ceil(b.get(0).children[0].getBoundingClientRect().width);a=c+Math.ceil(a.find(".textTail").get(0).getBoundingClientRect().width);c=a-c;b.css("max-width",
a);b.css("padding-right",c);b.css("margin-right",-c)};a.requireBinary=function(a){bg.have_binary()?a():LPPlatform.supportsBinary()?dialogs.confirmation.open({title:Strings.translateString("Install Binary Component"),text:Strings.translateString("This feature requires the binary version of this browser extension. Would you like to install it now?"),handler:function(){LPPlatform.installBinary()}}):dialogs.alert.open({title:Strings.translateString("Not Supported"),text:Strings.translateString("This feature requires an external binary component, which is currently not supported on this platform.")})};
a.isType=function(a,b){return Object.prototype.toString.call(a)==="[object "+b+"]"};a.getURLParams=function(){var a={},b=document.location.href.split("?");if(2===b.length){b=b[1].split("&");for(var d=0;d<b.length;++d){var f=b[d].split("=");2===f.length&&(a[f[0]]=f[1])}}return a};a.setContent=function(c,b){c.empty();if(b)if("string"===typeof b){for(var d=b.indexOf("<br/>");-1<d;)c.append(document.createTextNode(b.substring(0,d))),c.append(document.createElement("br")),b=b.substring(d+5),d=b.indexOf("<br/>");
c.append(document.createTextNode(b))}else if(a.isType(b,"Array")){d=0;for(var f=b.length;d<f;++d){var l=b[d];"string"===typeof l&&(l=a.createElement("p","dialogText",l));c.append(l)}}else c.append(b)};a.hideContextMenu=function(c){null!==c&&(c.removeClass("bottomAligned"),c.hide(),a.removeKeyBoardNavigation())};a.displayContextMenu=function(a,b){b=$(b);a.clientY>window.innerHeight/2?(b.addClass("bottomAligned"),b.css("bottom",window.innerHeight-a.clientY),b.css("top","")):(b.css("top",a.clientY),
b.css("bottom",""));b.css("left",a.clientX);b.show();return b};a.getProperties=function(a){var b=[],c;for(c in a)b.push(c);return b};a.openAlerts=function(){var c=function(b,c,f){return function(){"function"===typeof b&&b();a.openAlerts(c,f)}};return function(a,d){if(0<a.length){var b=a.shift();$.extend(b,{handler:c(b.handler,a,d),closeHandler:c(b.closeHandler,a,d)});dialogs[b.type].open(b)}else d&&d()}}();a.buildDialogItemContainer=function(c){for(var b=a.createElement("div","dialogItemContainer noSelect"),
d={display:VaultItemBaseDisplay.prototype.DISPLAY_LIST,allowDrag:!1,additionalItemClasses:"dialogItem noItemButtons"},f=0,l=c.length;f<l;++f){var e=c[f].newDisplayObject();b.appendChild(e.build(d))}return b};a.buildEmptyPlaceholder=function(c,b,d){return"ul"===d.tagName.toLocaleLowerCase()?a.createElement("li","emptyPlaceholder "+b,c):a.createElement("div","emptyPlaceholder "+b,c)};a.get_gmt_timestamp=function(){var a=(new Date).getTime();return parseInt(a/1E3)};a.ContextMenuItem=function(c,b){this.getAction=
function(){return c};this.build=function(d,f,l){var e=void 0!==b&&"undefined"!==typeof b.submenu&&b.submenu,h=null;void 0!==b&&"undefined"!==typeof b.divider&&b.divider&&(h="divider");e&&(h+=" subMenuOption");h=a.createElement("li",{"class":h,vaultaction:c});h.textContent=void 0===b||"undefined"===typeof b.text?Strings.Vault[Constants.CONTEXT_MENU_ITEMS[c]]:b.text;d.appendChild(h);e?(h.appendChild(a.createElement("div")),f=a.createElement("ul","subMenu"),h.appendChild(f),function(b,c){var f=null,
e=!1,g=function(){e&&(c.hide("fast"),a.addKeyBoardNavigation(d.children),Topics.get(Topics.LEFT_ARROW).unsubscribe(g))},h=function(a){e=!0;l(a);Topics.get(Topics.LEFT_ARROW).subscribe(g)};b.bind("click",h);b.bind("mouseenter",function(a){f=setTimeout(function(){h(a)},200)});b.bind("mouseleave",function(){f&&clearTimeout(f);g()})}($(h),$(f))):LPPlatform.addEventListener(h,"click",f)}};a.parseUserSpecificMenu=function(c,b){for(c=c.firstElementChild;c;){var d=c.getAttribute("user");if(null!==d){d=d.split("|");
for(var f=!0,e=0,g=d.length;e<g;++e)if(b===d[e]){f=!1;break}f?$(c).hide():c.removeAttribute("style")}a.parseUserSpecificMenu(c,b);c=c.nextElementSibling}};a.buildSentShareItems=function(a,b){var c=[];if(b)for(var f=0,e=b.length;f<e;++f){var g=b[f];"1"===g.state?c.push(new AcceptedSentSharedItem(a,g)):"2"===g.state?c.push(new DeclinedSentSharedItem(a,g)):c.push(new PendingSentSharedItem(a,g))}return c};a.openShareDialog=function(c,b){if(c&&1===c.length&&void 0===b)LPRequest.makeDataRequest(LPProxy.getSentShareData,
{params:{id:c[0].getID()},requestSuccessOptions:{closeDialog:!1},success:function(b){a.openShareDialog(c,b)},error:function(){Topics.get(Topics.DIALOG_LOADED).publish()}}),Topics.get(Topics.DIALOG_LOADING).publish();else if(b&&!dialogs.share.loadedJS())dialogs.share.loadJS(function(){a.openShareDialog(c,b)});else{var d=b?a.buildSentShareItems(c[0],b.sent[c[0].getID()]):null;dialogs.share.open(c,d,b?b.friends:null)}};a.objectsToArray=function(){for(var a=[],b=0,d=arguments.length;b<d;++b){var f=arguments[b],
e;for(e in f)a.push(f[e])}return a};a.createEventHandler=function(a){return function(b){a.handleEvent(b)}};a.getAttribute=function(a,b,d){for(var c=b.getAttribute(d);null===c&&b!==a;)if(b=b.parentElement,null!==b)c=b.getAttribute(d);else break;return c};a.removeDOMChildren=function(a){if(a)for(var b=a.childNodes.length;b--;)a.removeChild(a.lastChild)};a.removeDOMChildrenFrom=function(a,b){if(a)for(;b;){var c=b;b=b.nextElementSibling;a.removeChild(c)}};a.createElement=function(){return function(a,
b,d){var c=document.createElement(a);if("string"===typeof b||b instanceof Array)b={"class":b};if("input"===a||"textarea"===a)b=$.extend(b,{spellcheck:!1});if("object"===typeof b)for(var e in b){var g=b[e];if(void 0!==g&&null!==g){a=c;var h=e;g instanceof Array?a.setAttribute(h,g.join(" ")):a.setAttribute(h,g)}}void 0!==d&&(c.textContent=d);return c}}();a.addClass=function(a,b){if(null!==a){b instanceof Array&&(b=b.join(" "));var c=a.getAttribute("class");c&&(b=c+" "+b);a.setAttribute("class",b)}};
a.getOption=function(a,b,d){a&&void 0!==a[b]&&(d=a[b]);return d};(function(){var c=null,b=-1,d=null,e=null,l=null,g=null,h=null,k=null,p=[],r=null,q=function(a){return c&&-1<a&&a<c.length?c[a]:null},u=function(a,c){if(b!==a){var d=q(b);d&&d.removeClass("hover");k&&(d=k[b])&&"function"===typeof d.navigateFrom&&k[b].navigateFrom()}b=a;if(currentTarget=q(b))currentTarget.addClass("hover"),c&&h&&h.focusHandler&&h.focusHandler(currentTarget)},A=function(a){a=a.closest("[navindex]");var b=parseInt(a.attr("navindex")),
d=c[b];return d&&d.get(0)===a.get(0)?b:-1},z=function(a){g=!0;$(document.body).unbind("mousemove",z)};a.disableMouse=function(a){g&&(g=!1,$(document.body).bind("mousemove",z))};var v=function(a){g&&(a=$(a.target),u(A(a)))},w=function(a){g&&(a=$(a.target),a=A(a),(a=q(a))&&a.removeClass("hover"))},x=function(a){var b=a.offsetParent();b.scrollTop(Math.max(b.scrollTop()+b.height(),b.scrollTop()+a.position().top+a.outerHeight())-b.height())},B=function(a){var b=a.offsetParent();b.scrollTop(Math.min(b.scrollTop(),
b.scrollTop()+a.position().top))},C=function(d){if(b===c.length-1){var e=0;B(c[e])}else e=b+1,x(c[e]);u(e,!0);a.disableMouse();d.preventDefault();d.stopPropagation()},D=function(d){if(1>b){var e=c.length-1;x(c[e])}else e=b-1,K(e)?x(c[e]):B(c[e]);u(e,!0);a.disableMouse();d.preventDefault();d.stopPropagation()},K=function(a){if(!isFinite(a))return!1;a=c[a];if(!a)return!1;var b=a.offsetParent();if(!b)return!1;b=b.height();a=a.offset();return b<a.top},E=function(a){if(a){var b=new Event(d,{bubbles:!0});
a.get(0).dispatchEvent(b)}},F=function(a,b,c){return a&&(a=a[b])&&(c="arrow"+c.substr(0,1).toUpperCase()+c.substr(1).toLowerCase()+"Override","function"===typeof a[c])?a[c]():!0},G=function(a){var c=F(k,b,a);if(c)for(var d=p.length-1;0<=d&&c;--d)c=p[d],c=F(c.options.displayItems,c.navIndex,a);return c},L=G.bind(this,"left"),M=G.bind(this,"right"),H=function(){if(M()&&l){var c=q(b);if(c){if(e){var d=c.find(e);d.length&&(c=d)}E(c);a.disableMouse()}}return!l},I=function(){return L()},J=function(){var a;
a:{if(k&&(a=k[b])&&"function"===typeof a.keyboardEnterOverride){a=a.keyboardEnterOverride();break a}a=!0}a&&E(q(b));return!1};a.setNavIndex=function(a){u(a);(a=q())&&a.get(0).scrollIntoView()};a.getNavIndex=function(){return b};a.addKeyBoardNavigation=function(f,m){if(0<f.length){r={elements:f,options:m};c=[];b=-1;null===g&&(g=!0);d=a.getOption(m,"mouseEvent","click");e=a.getOption(m,"rightArrowSelector",null);l=a.getOption(m,"useRightArrow",!0);k=a.getOption(m,"displayItems",null);h=m;for(var t=
0,p=f.length;t<p;++t){var n=$(f[t]);n.attr("navindex",t);n.unbind("mouseenter",v);n.bind("mouseenter",v);n.unbind("mouseleave",w);n.bind("mouseleave",w);n.hasClass("hover")&&(b=t);c.push(n)}Topics.get(Topics.DOWN_ARROW).subscribe(C);Topics.get(Topics.UP_ARROW).subscribe(D);Topics.get(Topics.ENTER).subscribeFirst(J);Topics.get(Topics.RIGHT_ARROW).subscribeFirst(H);Topics.get(Topics.LEFT_ARROW).subscribeFirst(I);a.getOption(m,"selectFirst",!1)&&a.setNavIndex(0)}else a.removeKeyBoardNavigation()};a.removeKeyBoardNavigation=
function(){if(c)for(var a=0,b=c.length;a<b;++a)c[a].unbind("mouseenter",v),c[a].unbind("mouseleave",w);Topics.get(Topics.DOWN_ARROW).unsubscribe(C);Topics.get(Topics.UP_ARROW).unsubscribe(D);Topics.get(Topics.RIGHT_ARROW).unsubscribe(H);Topics.get(Topics.LEFT_ARROW).unsubscribe(I);Topics.get(Topics.ENTER).unsubscribe(J)};a.pushKeyBoardNavigation=function(c,d){r&&r.elements!==c&&(r.navIndex=b,p.push(r));a.removeKeyBoardNavigation();a.addKeyBoardNavigation(c,d)};a.popKeyBoardNavigation=function(){var b=
p.pop();b&&(a.removeKeyBoardNavigation(),a.addKeyBoardNavigation(b.elements,$.extend({},b.options,{selectFirst:!1})))}})();a.addZebraStriping=function(a){a=$(a).find("tr");for(var b=0,c=a.length;b<c;++b)0!==b%2?$(a[b]).addClass("odd"):$(a[b]).removeClass("odd")};var k=function(a){a=a.target.previousElementSibling;a.checked=!a.checked};a.buildCheckbox=function(c,b){var d=b?b.checkboxAttributes:void 0;d=$.extend(d,{"class":"checkbox",type:"checkbox"});d=a.createElement("input",d);c=a.createElement("label",
c,a.getOption(b,"text",void 0));a.getOption(b,"addClickHandler",!0)&&LPPlatform.addEventListener(c,"click",k);b=a.createElement("div");b.appendChild(d);b.appendChild(c);return b};a.buildRadioButton=function(c,b,d){c=a.createElement("input",{"class":"radio",type:"radio",name:c});b=a.createElement("label",b,d);LPPlatform.addEventListener(b,"click",k);d=a.createElement("div");d.appendChild(c);d.appendChild(b);return d};a.hasProperties=function(a){if(a)for(var b in a)if(a.hasOwnProperty(b))return!0;return!1};
a.createSelectElement=function(c,b){b=a.createElement("select",b);$(b).addClass("dialogInput selectDropdown");a.setSelectOptions(b,c);return b};a.setSelectOptions=function(c,b){a.removeDOMChildren(c);for(var d=0,e=b.length;d<e;++d){var l=b[d],g="object"===typeof l?l.value:l;c.appendChild(a.createElement("option",{value:g},"object"===typeof l&&l.label?l.label:g))}}})(LPTools);
Constants={ACTION_OPEN_MOVE_TO_SUB_FOLDER_MENU:"openMoveToSubFolderMenu",ACTION_OPEN_MOVE_TO_FOLDER_MENU:"openMoveToFolderMenu",ACTION_MOVE_TO_FOLDER:"moveToFolder",ACTION_SAVE:"save",ACTION_DELETE:"delete",ACTION_SHARE:"share",ACTION_COPY_USERNAME:"copyUsername",ACTION_COPY_PASSWORD:"copyPassword",ACTION_COPY_ADDRESS_1:"copyAddress1",ACTION_COPY_ADDRESS_2:"copyAddress2",ACTION_COPY_CITY_SLASH_TOWN:"copyCitySlashTown",ACTION_COPY_ZIP_SLASH_POSTAL_CODE:"copyZipSlashPostalCode",ACTION_COPY_EMAIL_ADDRESS:"copyEmailAddress",
ACTION_COPY_PHONE_NUMBER:"copyPhoneNumber",ACTION_COPY_BANK_NAME:"copyBankName",ACTION_COPY_ACCOUNT_NUMBER:"copyAccountNumber",ACTION_COPY_ROUTING_NUMBER:"copyRoutingNumber",ACTION_COPY_NAME_ON_CARD:"copyNameOnCard",ACTION_COPY_SECURITY_CODE:"copySecurityCode",ACTION_COPY_GROUP_ID:"copyGroupId",ACTION_COPY_MEMBER_ID:"copyMemberId",ACTION_COPY_POLICY_NUMBER:"copyPolicyNumber",ACTION_COPY_MEMBERSHIP_NUMBER:"copyMembershipNumber",ACTION_COPY_NUMBER:"copyNumber",ACTION_COPY_LICENSE_KEY:"copyLicenseKey",
ACTION_COPY_ORDER_NUMBER:"copyOrderNumber",ACTION_COPY_SSH_PASSPHRASE:"copySshPassphrase",ACTION_COPY_SSH_PUBLIC_KEY:"copySshPublicKey",ACTION_COPY_HOSTNAME:"copyHostname",ACTION_COPY_NOTE_USERNAME:"copyUsername",ACTION_COPY_NOTE_PASSWORD:"copyPassword",ACTION_COPY_URL:"copyURL",ACTION_EDIT:"edit",ACTION_LAUNCH:"launch",ACTION_GO_TO_URL:"goToURL",ACTION_TOGGLE_OPEN:"toggleOpen",ACTION_RENAME:"rename",ACTION_CONVERT:"convert",ACTION_ACCEPT:"acceptShare",ACTION_REJECT:"rejectShare",ACTION_ENABLE:"enable",
ACTION_TOGGLE_SELECT:"toggleSelect",ACTION_CREATE_SUB_FOLDER:"createSubFolder",ACTION_OPEN_ALL:"openAll",ACTION_OPEN_MORE_OPTIONS:"openMoreOptions",ACTION_OPEN_IN_CONTEXT_OPTIONS:"openInContextOptions",ACTION_COPY_NOTE:"copyNote",ACTION_FILL:"fillForm",ACTION_OPEN:"open",ACTION_REVOKE:"revoke",ACTION_EMAIL:"email",ACTION_CANCEL:"cancel",ACTION_REMOVE:"remove",ACTION_PURGE:"purge",ACTION_PURGE_SHARED_FOLDER:"purgeSharedFolder",ACTION_RESTORE:"restore",ACTION_RESTORE_SHARED_FOLDER:"restoreSharedFolder",
ACTION_UNLINK:"unlink",ACTION_STOP_DOWNLOADING:"stopDownloading",ACTION_START_DOWNLOADING:"startDownloading",ACTION_FILL_SITE:"fillSite",ACTION_CLONE:"clone",ACTION_ADD:"add",ACTION_MANAGE:"manage",ACTION_ACCESS:"access",ACTION_COPY_KEY:"copyKey",ACTION_DASHBOARD:"dashboard",ACTION_UPGRADE:"upgrade",ACTION_DO_NOTHING:"doNothing",USER_FREE:"Free User",USER_PREMIUM:"Premium User",USER_PREMIUM_TRIAL:"Premium Trial User",USER_ENTERPRISE:"Enterprise User",USER_ENTERPRISE_ADMIN:"Enterprise Admin",USER_ENTERPRISE_ROLE:"Enterprise Role User",
USER_TEAMS:"Teams User",USER_TEAMS_ADMIN:"Teams Admin",USER_FAMILY:"Family User",USER_FAMILY_ADMIN:"Family Admin",UNAFFILIATED_COMPANY_ID:"0",EmailAddressRegularExpression:/[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*/g};
(function(a){a.ACTION_BUTTONS={};a.ACTION_BUTTONS[a.ACTION_EDIT]={title:"EDIT",css:a.ACTION_EDIT};a.ACTION_BUTTONS[a.ACTION_SHARE]={title:"SHARE",css:a.ACTION_SHARE};a.ACTION_BUTTONS[a.ACTION_DELETE]={title:"DELETE",css:a.ACTION_DELETE};a.ACTION_BUTTONS[a.ACTION_ACCEPT]={title:"ACCEPT",css:a.ACTION_ACCEPT};a.ACTION_BUTTONS[a.ACTION_REJECT]={title:"REJECT",css:a.ACTION_REJECT};a.ACTION_BUTTONS[a.ACTION_LAUNCH]={title:"LAUNCH",css:null};a.ACTION_BUTTONS[a.ACTION_ENABLE]={title:"ENABLE",css:null};a.ACTION_BUTTONS[a.ACTION_ACCESS]=
{title:"REQUEST_ACCESS",css:null};a.ACTION_BUTTONS[a.ACTION_REVOKE]={title:"REVOKE",css:a.ACTION_REJECT};a.ACTION_BUTTONS[a.ACTION_EMAIL]={title:"RESEND",css:a.ACTION_EMAIL};a.ACTION_BUTTONS[a.ACTION_CANCEL]={title:"CANCEL_INVITE",css:a.ACTION_REJECT};a.ACTION_BUTTONS[a.ACTION_REMOVE]={title:"REMOVE",css:a.ACTION_REJECT};a.ACTION_BUTTONS[a.ACTION_PURGE]={title:"PURGE",css:a.ACTION_DELETE};a.ACTION_BUTTONS[a.ACTION_PURGE_SHARED_FOLDER]={title:"PURGE",css:a.ACTION_DELETE};a.ACTION_BUTTONS[a.ACTION_RESTORE]=
{title:"RESTORE",css:a.ACTION_RESTORE};a.ACTION_BUTTONS[a.ACTION_RESTORE_SHARED_FOLDER]={title:"RESTORE",css:a.ACTION_RESTORE};a.ACTION_BUTTONS[a.ACTION_MANAGE]={title:"MANAGE",css:a.ACTION_EDIT};a.ACTION_BUTTONS[a.ACTION_UNLINK]={title:"UNLINK",css:a.ACTION_DELETE};a.CONTEXT_MENU_ITEMS={};a.CONTEXT_MENU_ITEMS[a.ACTION_EDIT]="EDIT";a.CONTEXT_MENU_ITEMS[a.ACTION_SHARE]="SHARE";a.CONTEXT_MENU_ITEMS[a.ACTION_DELETE]="DELETE";a.CONTEXT_MENU_ITEMS[a.ACTION_GO_TO_URL]="GO_TO_URL";a.CONTEXT_MENU_ITEMS[a.ACTION_COPY_USERNAME]=
"COPY_USERNAME";a.CONTEXT_MENU_ITEMS[a.ACTION_COPY_PASSWORD]="COPY_PASSWORD";a.CONTEXT_MENU_ITEMS[a.ACTION_COPY_URL]="COPY_URL";a.CONTEXT_MENU_ITEMS[a.ACTION_OPEN_MOVE_TO_FOLDER_MENU]="MOVE_TO_FOLDER";a.CONTEXT_MENU_ITEMS[a.ACTION_OPEN_MOVE_TO_SUB_FOLDER_MENU]="MOVE_TO_SUB_FOLDER";a.CONTEXT_MENU_ITEMS[a.ACTION_ACCEPT]="ACCEPT";a.CONTEXT_MENU_ITEMS[a.ACTION_REJECT]="REJECT";a.CONTEXT_MENU_ITEMS[a.ACTION_ENABLE]="ENABLE";a.CONTEXT_MENU_ITEMS[a.ACTION_RENAME]="RENAME_FOLDER";a.CONTEXT_MENU_ITEMS[a.ACTION_CONVERT]=
"CONVERT_FOLDER_TO_LEGACY";a.CONTEXT_MENU_ITEMS[a.ACTION_CREATE_SUB_FOLDER]="CREATE_SUB_FOLDER";a.CONTEXT_MENU_ITEMS[a.ACTION_OPEN_ALL]="OPEN_ALL";a.CONTEXT_MENU_ITEMS[a.ACTION_COPY_NOTE]="COPY_NOTE";a.CONTEXT_MENU_ITEMS[a.ACTION_COPY_KEY]="COPY_KEY";a.CONTEXT_MENU_ITEMS[a.ACTION_FILL]="FILL";a.CONTEXT_MENU_ITEMS[a.ACTION_OPEN]="OPEN";a.CONTEXT_MENU_ITEMS[a.ACTION_SAVE]="SAVE";a.CONTEXT_MENU_ITEMS[a.ACTION_REVOKE]="REVOKE";a.CONTEXT_MENU_ITEMS[a.ACTION_EMAIL]="RESEND";a.CONTEXT_MENU_ITEMS[a.ACTION_CANCEL]=
"CANCEL_INVITE";a.CONTEXT_MENU_ITEMS[a.ACTION_REMOVE]="REMOVE";a.CONTEXT_MENU_ITEMS[a.ACTION_PURGE]="PURGE";a.CONTEXT_MENU_ITEMS[a.ACTION_PURGE_SHARED_FOLDER]="PURGE";a.CONTEXT_MENU_ITEMS[a.ACTION_RESTORE]="RESTORE";a.CONTEXT_MENU_ITEMS[a.ACTION_RESTORE_SHARED_FOLDER]="RESTORE";a.CONTEXT_MENU_ITEMS[a.ACTION_UNLINK]="UNLINK_PERSONAL";a.CONTEXT_MENU_ITEMS[a.ACTION_STOP_DOWNLOADING]="STOP_DOWNLOADING";a.CONTEXT_MENU_ITEMS[a.ACTION_START_DOWNLOADING]="START_DOWNLOADING";a.CONTEXT_MENU_ITEMS[a.ACTION_FILL_SITE]=
"AUTO_FILL";a.CONTEXT_MENU_ITEMS[a.ACTION_CLONE]="CLONE";a.CONTEXT_MENU_ITEMS[a.ACTION_MANAGE]="MANAGE_FOLDER";a.CONTEXT_MENU_ITEMS[a.ACTION_ACCESS]="REQUEST_ACCESS";a.CONTEXT_MENU_ITEMS[a.ACTION_DASHBOARD]="OPEN_DASHBOARD";a.CONTEXT_MENU_ITEMS[a.ACTION_UPGRADE]="UPGRADE_PREMIUM";a.HISTORY_TYPES={PASSWORD:0,USERNAME:1,NOTE:2}})(Constants);
(function(a){a.fn.extend({LP_show:function(){this.removeClass("displaynone");return this},LP_hide:function(){this.addClass("displaynone");return this},LP_removeAttr:function(a){for(var e=0,c=this.length;e<c;++e)this.get(e).removeAttribute(a)},LP_addSearchHandlers:function(e,k){var c=a(LPTools.createElement("div","searchInputContainer"));this.before(c);c.append(this);var b="searchCloseButton";e&&(b+=" "+e);var d=a(LPTools.createElement("div",{"class":b,title:Strings.translateString("Clear Search")}));
c.append(d);var f,l=function(a){clearTimeout(f);f=setTimeout(function(){try{k(a)}catch(h){LPPlatform.logException(h)}},150)};(function(a){d.bind("click",function(b){a.val("");b.stopPropagation();b.preventDefault()})})(this);this.LP_input("search",function(a){0<a.length?c.addClass("populated"):c.removeClass("populated");l(a)});return this},LP_createToggle:function(){return function(){for(var a=0,k=this.length;a<k;++a){var c=this.get(a);if("INPUT"===c.nodeName&&"checkbox"===c.getAttribute("type")&&
"LABEL"===c.nextElementSibling.nodeName){var b=LPTools.createElement("div","toggleButton");b.appendChild(LPTools.createElement("div"));c.nextElementSibling.appendChild(b)}}return this}}(),LP_addPasswordEye:function(){var e=function(a,b,d){a.passwordShown=!1;a.attr("type","password");b.attr("title",Strings.Vault.SHOW_PASSWORD);b.removeClass("selected");d&&b.text(Strings.Vault.SHOW)},k=function(a,b,d){switch(a.attr("type")){case "password":a.passwordShown=!0;a.attr("type","text");b.attr("title",Strings.Vault.HIDE_PASSWORD);
b.addClass("selected");d&&b.text(Strings.Vault.HIDE);break;case "text":e(a,b,d)}d&&a.css("padding-right",b.outerWidth())};return function(c){this.addClass("password");var b=a(LPTools.createElement("div","relative"));this.before(b);b.append(this);b.css({margin:this.css("margin")});this.css("margin","0");var d=a(LPTools.createElement("button",{"class":"showPassword",title:Strings.Vault.SHOW_PASSWORD}));b.append(d);(function(f,l){function g(){0===f.val().length?d.addClass("displaynone"):d.removeClass("displaynone")}
var h=LPTools.getOption(c,"textual",!1);h?(d.addClass("textual"),d.text(Strings.Vault.SHOW),f.one("focus",function(){f.css("padding-right",d.outerWidth())})):d.addClass("iconButton");d.bind("click",function(){"password"===f.attr("type")&&l?l(function(){k(f,d,h)}):k(f,d,h)});f.hidePassword=function(){e(f,d,h)};if(LPTools.getOption(c,"includeGenerateButton",!1)){f.LP_input("passwordGenerate",function(a){a?b.removeClass("empty"):(f.hidePassword(),b.addClass("empty"))});var y=a(LPTools.createElement("button",
{"class":"generatePassword iconButton",title:Strings.Vault.GENERATE_PASSWORD}));b.append(y);y.bind("click",function(){(bg.get("LPContentScriptFeatures").better_generate_password_enabled?dialogs.betterGeneratePassword:dialogs.generatePassword).open({fillGenerated:!1,saveOptions:{source:"vault"}})})}LPTools.getOption(c,"showOnlyIfPopulated",!1)&&(g(),f.bind("keyup",g))})(this,LPTools.getOption(c,"checkPermissionHandler",null));this.val(this.val());return this}}(),LP_reflow:function(){for(var a=0;a<
this.length;++a)this.get(a).offsetHeight;return this},LP_scrollParent:function(){if(1===this.length)for(var e=this.get(0).parentElement;e;){var k=a(e);if("auto"===k.css("overflow")&&k.css("max-height")){var c=e;break}e=e.parentElement}return a(c)},LP_input:function(a,k){var c=this;a=a?"."+a:"";c.unbind("keypress"+a);c.unbind("keyup"+a);c.unbind("input"+a);var b=function(a){a=a.which;31<a&&k(c.val()+String.fromCharCode(a))};c.bind("keypress"+a,b);var d=function(a){switch(a.keyCode||a.which){case 8:case 46:k(c.val())}};
c.bind("keyup"+a,d);var e=function(){c.unbind("keypress"+a,b);c.unbind("keyup"+a,d);c.unbind("input"+a,e)};c.bind("input"+a,e);c.bind("input"+a,function(){k(c.val())});c.val=function(a){return function(){1===arguments.length&&k(arguments[0]);return a.apply(c,arguments)}}(this.val)}})})(jQuery);NotifyException=function(a){Topics.get(Topics.ERROR).publish(a);this.message=a;this.stack=Error().stack};NotifyException.prototype=Object.create(Error.prototype);NotifyException.prototype.name="InvalidArgumentException";
NotifyException.prototype.constructor=NotifyException;AttachmentKeyException=function(){NotifyException.call(this,Strings.translateString("Could not decrypt attachment key."))};AttachmentKeyException.prototype=Object.create(NotifyException.prototype);AttachmentKeyException.prototype.name="AttachmentKeyException";AttachmentKeyException.prototype.constructor=AttachmentKeyException;
//# sourceMappingURL=newvault_tools_js.js.map