LPFeatures=function(){var d=$(document.body),b=function(a){a=bg.get("g_prefoverrides")[a];return void 0===a||"1"===a},e=function(a,b,c){d.removeClass("no-feature-"+a);d.removeClass("feature-"+a);"undefined"!==typeof c&&!0!==c||b?"undefined"!==typeof c&&!1!==c||!b||d.addClass("feature-"+a):d.addClass("no-feature-"+a)},f=function(){return null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").omaria?!1:bg.get("LPContentScriptFeatures").omaria},
g=function(){return null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").safari_legacy_messaging?!1:bg.get("LPContentScriptFeatures").safari_legacy_messaging};return{updateFeatures:function(a){for(var b in a){var c=b;var d=bg.get("g_prefoverrides");switch(c){case "showcredmon":c=bg.get("g_showcredmon");break;default:c=d&&d[c]}"boolean"===typeof c&&(c=c?"1":"0");"undefined"!==typeof prevValue&&e(b,"1"===
c,a[b])}e("omaria",f());e("safariLegacyMessaging",g());bg.get("g_new_settings_enabled")&&$("#newSettingsMenuItem").addClass("visible")},allowIndividualSharing:function(){return this.allowShare()&&!this.allowShareOnlyFolders()},allowSharedFolders:function(){return this.allowShare()},allowClipboardCopy:function(){return bg.can_copy_to_clipboard()},allowImport:function(){return b("import")},allowShare:function(){return b("share")},allowShareOutsideEnterprise:function(){return b("shareout")},allowShareOnlyFolders:function(){return"1"===
bg.get("g_prefoverrides").share_onlyfolders},allowShareDomain:function(a){return!0},allowPasswordRevert:function(){return b("revert")},allowNotes:function(){return b("show_notes")},allowFingerprint:function(){return b("show_fingerprint")},allowBookmarklets:function(){return b("bookmarklets")},allowHint:function(){return b("hint")},allowGift:function(){var a=new Date;return 10===a.getMonth()&&25<=a.getDate()||11===a.getMonth()&&25>=a.getDate()?!0:!1},allowLaunchApplication:function(){return bg.canLaunchApplication()},
allowNewSettings:function(){return bg.get("g_new_settings_enabled")},allowTryFamilies:function(){var a=null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").try_families_enabled?!1:bg.get("LPContentScriptFeatures").try_families_enabled;return a},restrictOneToOneSharing:function(){var a=null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").one_to_one_sharing_restricted?
!1:bg.get("LPContentScriptFeatures").one_to_one_sharing_restricted;return a},pbkdf2IterartionsMigration:function(){return bg.get("LPContentScriptFeatures")&&!!bg.get("LPContentScriptFeatures").pbkdf2_iterations_migration_enabled},isUpgradeButtonTestEnabled:function(){var a=null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").upgrade_button_test?!1:bg.get("LPContentScriptFeatures").upgrade_button_test;
return a},isDownloadExtensionWebPromptEnabled:function(){var a=null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").download_extension_web_prompt?!1:bg.get("LPContentScriptFeatures").download_extension_web_prompt;return a},restrictEmergencyAccessForFree:function(){var a=null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").emergency_access_restricted?
!1:bg.get("LPContentScriptFeatures").emergency_access_restricted;return a},allowLicenseExpiration:function(){var a=null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").license_expiration?!1:bg.get("LPContentScriptFeatures").license_expiration;return a},allowOmarIA:f,allowMigrationOptIn:function(){return null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==
typeof bg.get("LPContentScriptFeatures").migration_opt_in?!1:bg.get("LPContentScriptFeatures").migration_opt_in},allowFormfillMigration:function(){return!!bg.get("LPContentScriptFeatures").formfill_migration},allowOmarDrawer:function(){return null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").omardrawer?!1:bg.get("LPContentScriptFeatures").omardrawer},isDogfood:function(){return null==bg.get("LPContentScriptFeatures")||
"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").isDogfood?!1:bg.get("LPContentScriptFeatures").isDogfood},safari_legacy_messaging:g,secondary_onboarding_visible:function(){return null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").secondary_onboarding_visible?!1:bg.get("LPContentScriptFeatures").secondary_onboarding_visible},hide_cloud_apps_policy_enabled:function(){return null==
bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").hide_cloud_apps_policy_enabled?!1:bg.get("LPContentScriptFeatures").hide_cloud_apps_policy_enabled},familiesProvisioningUpdate:function(){return null==bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures")||"undefined"==typeof bg.get("LPContentScriptFeatures").families_provisioning_update?!1:bg.get("LPContentScriptFeatures").families_provisioning_update},
canBackgroundOpenPopover:function(){return LPPlatform.canBackgroundOpenPopover()}}}();
//# sourceMappingURL=newvault_features_js.js.map