DialogInput=function(){var x=function(a){var b={},d;for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]instanceof h?x(a[d]):!0);return b},h=function(){};h.prototype.validate=function(){var a=!0,b;for(b in this)this.hasOwnProperty(b)&&(a=this[b].validate()&&a);return a};h.prototype.clear=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clear()};h.prototype.clearErrors=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clearErrors()};h.prototype.adjustView=function(){for(var a in this)if(this.hasOwnProperty(a)){var b=
this[a];"function"===typeof b.adjustView&&b.adjustView()}};h.prototype.getValue=function(a){var b={},d;for(d in this)this.hasOwnProperty(d)&&(b[d]=this[d].getValue(a));return b};h.prototype.setValue=function(a){for(var b in this)this.hasOwnProperty(b)&&this[b].setValue(void 0===a[b]?"":a[b])};h.prototype.hasError=function(){for(var a in this)if(this.hasOwnProperty(a)&&this[a].hasError())return!0;return!1};var r=function(a){this.items={};this.groupName=a};r.prototype.getValue=function(){for(var a in this.items)if(this.items[a].prop("checked"))return a};
r.prototype.setValue=function(a){if(a=this.items[a])a.prop("checked",!0);else for(var b in this.items)this.items[b].prop("checked",!1)};r.prototype.addRadioInput=function(a){var b=a.attr("value");if(b){if(a.attr("name")!==this.groupName)throw"RadioGroup member must have the same name attribute as the other radio inputs in the group (based on dialogField)!";this.items[b]=a}else throw"RadioGroup member must have a value!";};var f=function(){this._errors=[];this._errorOptions=this._errorContainer=null;
this._hasError=!1};f.prototype.postValidate=function(){(this._hasError=0<this._errors.length)&&this._errorContainerWrapper.find("input,select,textarea").bind("focus",this.focusHandler).bind("blur",this.blurHandler).bind("change",this.changeHandler)};f.prototype.hasError=function(){return this._hasError};f.prototype.buildError=function(){var a=this.getElement(),b={element:a,alignTop:"SELECT"===this.input.prop("nodeName").toUpperCase()};"checkbox"===a.attr("type")&&(b.element=b.element.add(a.next()),
b.static=!0);return this.buildErrorElement(b)};f.prototype.buildErrorElement=function(a){this._errorOptions=a=$.extend(this.getDialog().getErrorOptions(),a);var b=this._errorContainerWrapper=$(LPTools.createElement("div","relative"));this._errorContainer=$(LPTools.createElement("div","dialogErrorContainer"));a.element.before(b);a.static&&b.addClass("staticError");a.alignTop&&this._errorContainer.addClass("alignTop");a.static&&!a.alignTop?(b.append(a.element),b.append(this._errorContainer)):(b.append(this._errorContainer),
b.append(a.element));var d=this.getDialog();this.focusHandler=function(){b.addClass("focus")};this.blurHandler=function(){b.removeClass("focus")};this.changeHandler=function(){d.performValidate({data:d.getData(),errorsOnly:!0})}};f.prototype.addError=function(a,b){b=this.dialog=this.getDialog()||b;if(!this.disabled&&!LPTools.getOption(b.validateOptions,"errorsOnly",!1)||this.hasError())this._hasError=!0,this._errors.push(a),this.buildErrorMessage()};f.prototype.clearErrors=function(){this._errors=
[];this._errorContainer&&(this._errorContainer.empty(),this._errorContainerWrapper.removeClass("error"),this._errorContainerWrapper.find("input,select,textarea").unbind("focus",this.focusHandler).unbind("blur",this.blurHandler).unbind("change",this.changeHandler))};f.prototype.clear=function(){this._hasError=!1};f.prototype.adjustView=function(){};f.prototype.buildErrorMessage=function(){this._errorContainer||this.buildError();this._errorContainerWrapper.addClass("error");this._errors.forEach(function(a){var b=
LPTools.createElement("div","dialogError");b.appendChild(LPTools.createElement("div","validation-img warning"));LPTools.getOption(this._errorOptions,"showErrorLabel",!0)&&b.appendChild(LPTools.createElement("span","errorLabel",Strings.translateString("ERROR")+": "));b.appendChild(LPTools.createElement("span","",a));this._errorContainer.append(b)},this)};f.prototype.getDialog=function(){return this.dialog};f.prototype.getElement=function(){return this.input};var c=function(a,b){f.call(this);this.setElement(a);
this.disabled=!1;this.dialog=b;this.radioGroup=null};c.prototype=Object.create(f.prototype);c.prototype.constructor=c;c.prototype.getNativeElement=function(){return this.getElement().get(0)};c.prototype.setElement=function(a){this.input=a instanceof $?a:$(a);"SELECT"===this.input.prop("nodeName")&&this.input.prepend(LPTools.createElement("option",{value:""},""))};c.prototype.default=function(){this.setValue("")};c.prototype.validate=function(){return!0};c.prototype.focus=function(){this.input.focus()};
c.prototype.disable=function(){this.disabled||(this.disabled=!0,this.input.prop("disabled",!0))};c.prototype.enable=function(){this.disabled&&(this.disabled=!1,this.input.prop("disabled",!1))};c.prototype.clear=function(){f.prototype.clear.apply(this,arguments);if(this.input){switch(this.input.attr("type")){case "checkbox":case "radio":this.setValue(!1);break;default:this.setValue("")}this.input.passwordShown&&this.input.hidePassword()}};c.prototype.getValue=function(){switch(this.input.attr("type")){case "radio":if(this.radioGroup)return this.radioGroup.getValue();
case "checkbox":return this.input.prop("checked");default:return this.input.val()||""}};c.prototype.setValue=function(a){var b=this.getValue();switch(this.input.attr("type")){case "radio":if(this.radioGroup)return this.radioGroup.setValue(a);case "checkbox":this.input.prop("checked",a);break;default:this.input.val(a)}b!==a&&this.fireOnChange()};c.prototype.addRadioInput=function(a,b){null===this.radioGroup&&(this.radioGroup=new r(a),this.radioGroup.addRadioInput(this.input));this.radioGroup.addRadioInput(b instanceof
$?b:$(b))};c.prototype.fireOnChange=function(){if(this.onChangeCallback)this.onChangeCallback(this.getValue())};c.prototype.onChange=function(a){this.onChangeCallback=a;(function(a){a.getElement().bind("change",function(){a.fireOnChange()})})(this)};c.prototype.buildInputElement=function(){return this.getNativeElement()};c.prototype.adjustView=function(){};var e=function(a,b,d){this.field=a;this.inputObject=b;d=d||{};this.label=void 0===d.label?Strings.translateString(a):d.label?Strings.translateString(d.label):
null;this.isTopAlign=d.topAlign};e.prototype.build=function(){var a="settingLabel";this.isTopAlign&&(a+=" topAlign");var b=LPTools.createElement("tr"),d=LPTools.createElement("td");this.label&&b.appendChild(LPTools.createElement("td",a,this.label));b.appendChild(d);d.appendChild(this.inputObject.buildInputElement());return b};e.prototype.getNativeElement=function(){return this.inputObject.getNativeElement()};e.prototype.setElement=function(a){this.inputObject.setElement(a)};e.prototype.default=function(){this.inputObject.default()};
e.prototype.clearErrors=function(){this.inputObject.clearErrors()};e.prototype.validate=function(){return this.inputObject.validate()};e.prototype.focus=function(){this.inputObject.focus()};e.prototype.disable=function(){this.inputObject.disable()};e.prototype.enable=function(){this.inputObject.enable()};e.prototype.clear=function(){this.inputObject.clear()};e.prototype.getValue=function(){return this.inputObject.getValue()};e.prototype.setValue=function(a){this.inputObject.setValue(a)};e.prototype.fireOnChange=
function(){this.inputObject.fireOnChange()};e.prototype.onChange=function(a){this.inputObject.onChange(a)};e.prototype.adjustView=function(){this.inputObject.adjustView()};var m=function(a){c.call(this,LPTools.createElement("input",{"class":"dialogInput",type:"text"}));this.options=a};m.prototype=Object.create(c.prototype);m.prototype.constructor=m;m.prototype.buildInputElement=function(){var a=this.getNativeElement(),b=LPTools.getOption(this.options,"inputButton",null);if(b){this.dialog=this.dialog||
dialogs.note.getDialog();var d=LPTools.createElement("div","relative");d.appendChild(a);this.inputButtonElement=LPTools.createElement("button","dialogInputButton",b);var c=LPTools.getOption(this.options,"inputButtonHandler",null);c&&function(a){LPPlatform.addEventListener(a.inputButtonElement,"click",function(){c.apply(a)})}(this);d.appendChild(this.inputButtonElement);return d}return a};m.prototype.adjustView=function(){if(this.inputButtonElement){var a=parseInt(this.input.css("padding-right"));
this.input.css("padding-right",a+$(this.inputButtonElement).outerWidth())}};var p=function(){c.call(this,LPTools.createElement("input",{"class":"dialogInput",type:"password"}))};p.prototype=Object.create(c.prototype);p.prototype.constructor=p;p.prototype.buildInputElement=function(){this.input.LP_addPasswordEye({includeGenerateButton:!0});var a=this.input.parents();return a[a.length-1]};var n=function(a,b){this.options=b||{};c.call(this,LPTools.createElement("textarea",["dialogInput",a]))};n.prototype=
Object.create(c.prototype);n.prototype.constructor=n;n.prototype.buildInputElement=function(){var a=this.getNativeElement(),b=LPTools.getOption(this.options,"inputButton",null);if(b){this.dialog=this.dialog||dialogs.note.getDialog();var d=LPTools.createElement("div","relative");d.appendChild(a);this.inputButtonElement=LPTools.createElement("button","dialogInputButton copy",b);var c=LPTools.getOption(this.options,"inputButtonHandler",null);c&&function(a){LPPlatform.addEventListener(a.inputButtonElement,
"click",function(){c.apply(a)})}(this);d.appendChild(this.inputButtonElement);return d}return a};n.prototype.adjustView=function(){if(this.inputButtonElement){var a=parseInt(this.input.css("padding-right"));this.input.css("padding-right",a+$(this.inputButtonElement).outerWidth())}};var q="January February March April May June July August September October November December".split(" "),A="01 02 03 04 05 06 07 08 09 10 11 12".split(" "),w=[];(function(){for(var a=0,b=q.length;a<b;++a){var c=a+1;w.push((10>
c?"0"+c:c)+" - "+Strings.translateString(q[a]))}})();var y=[{value:"",label:""}];(function(){for(var a=0,b=q.length;a<b;++a)y.push({value:q[a],label:w[a]})})();var z=[{value:"",label:""}];(function(){for(var a=0,b=q.length;a<b;++a)z.push({value:A[a],label:w[a]})})();var g=function(a){c.call(this);this.includeDay=LPTools.getOption(a,"includeDay",!0)};g.prototype=Object.create(c.prototype);g.prototype.constructor=g;g.prototype.buildError=function(){return this.buildErrorElement({element:$(this.container)})};
g.prototype.buildInputElement=function(){var a="";this.includeDay||(a="monthYearDate");this.container=LPTools.createElement("div",a);a=LPTools.createElement("div","dateInputMonth");this.monthInput=LPTools.createSelectElement(this.getMonthOptions());this.dayInput=null;this.includeDay&&(this.dayInput=LPTools.createElement("input",{"class":"dialogInput dateInputDay",type:"text"}));this.yearInput=LPTools.createElement("input",{"class":"dialogInput dateInputYear",type:"text"});a.appendChild(this.monthInput);
this.container.appendChild(a);null!==this.dayInput&&this.container.appendChild(this.dayInput);this.container.appendChild(this.yearInput);return this.container};g.prototype.clear=function(){this.monthInput&&(this.monthInput.value="");this.dayInput&&(this.dayInput.value="");this.yearInput&&(this.yearInput.value="")};g.prototype.getValue=function(){return this.toString()};g.prototype.setValue=function(a){a=this.parse(a);var b="",c="",e="";a&&(b=a.shift(),2===a.length&&(c=a.shift()),e=a.shift());this.monthInput.value=
b;this.includeDay&&(this.dayInput.value=c);this.yearInput.value=e};var k=function(a){g.call(this,a)};k.prototype=Object.create(g.prototype);k.prototype.constructor=k;k.prototype.toString=function(){var a=this.monthInput.value;this.dayInput&&(a+=","+this.dayInput.value);return a+=","+this.yearInput.value};k.prototype.parse=function(a){return a?a.split(","):null};k.prototype.getMonthOptions=function(){return y};var l=function(a){g.call(this,a)};l.prototype=Object.create(g.prototype);l.prototype.constructor=
l;l.prototype.toString=function(){var a=this.yearInput.value+"-"+this.monthInput.value;this.includeDay&&(a+="-"+this.dayInput.value);if("-"===a||"--"===a)a="";return a};l.prototype.parse=function(a){return a?(a=a.split("-"),a.push(a.shift()),a):null};l.prototype.getMonthOptions=function(){return z};var t=function(){c.call(this,LPTools.createTimezoneSelect())};t.prototype=Object.create(c.prototype);t.prototype.constructor=t;var u=function(a){c.call(this,LPTools.createSelectElement(a))};u.prototype=
Object.create(c.prototype);u.prototype.constructor=u;var v=function(){c.call(this,LPTools.createCountrySelect())};v.prototype=Object.create(c.prototype);v.prototype.constructor=v;return{ErrorDisplayInput:f,Input:c,LabelledInput:e,TextInput:m,PasswordInput:p,TextArea:n,NumericDateInput:l,AlphaDateInput:k,NestedFields:h,SelectInput:u,TimezoneInput:t,CountryInput:v,getProperties:x}}();
//# sourceMappingURL=newvault_dialogFields_js.js.map