Strings={};
(function(e){if("undefined"!==typeof Topics){var g=!1;Topics.get(Topics.INITIALIZED).subscribe(function(){g||(e.translateStrings(e.Vault),g=!0)});Topics.get(Topics.CONTENT_SCRIPT_ADD_SITE_DIALOG_OPENED).subscribe(function(){g||(e.translateStrings(e.Vault),g=!0)})}e.Vault={EDIT:"Edit",SHARE:"Share",DELETE:"Delete",LAUNCH:"Launch",ADMIN_CONSOLE:"Admin Console",HELP_CENTER:"Help Center",ATTEND_WEBINAR:"Attend Webinar",ACCOUNT_SETTINGS:"Account Settings",LOGOUT:"Logout",ACCEPT:"Accept",REJECT:"Reject",ENABLE:"Enable",
COPY_USERNAME:"Copy Username",COPY_PASSWORD:"Copy Password",COPY_ADDRESS_1:"Copy Address 1",COPY_ADDRESS_2:"Copy Address 2",COPY_CITY_SLASH_TOWN:"Copy City / Town",COPY_ZIP_SLASH_POSTAL_CODE:"Copy ZIP / Postal Code",COPY_EMAIL_ADDRESS:"Copy Email Address",COPY_PHONE_NUMBER:"Copy Phone Number",COPY_BANK_NAME:"Copy Bank Name",COPY_ACCOUNT_NUMBER:"Copy Account Number",COPY_ROUTING_NUMBER:"Copy Routing Number",COPY_NAME_ON_CARD:"Copy Name on Card",COPY_SECURITY_CODE:"Copy Security Code",COPY_LICENSE_NUMBER:"Copy License Number",
COPY_POLICY_NUMBER:"Copy Policy Number",COPY_GROUP_ID:"Copy Group ID",COPY_MEMBER_ID:"Copy Member ID",COPY_MEMBERSHIP_NUMBER:"Copy Membership Number",COPY_NUMBER:"Copy Number",COPY_LICENSE_KEY:"Copy License Key",COPY_ORDER_NUMBER:"Copy Order Number",COPY_SSH_PASSPHRASE:"Copy Passphrase",COPY_SSH_PUBLIC_KEY:"Copy Public Key",COPY_HOSTNAME:"Copy Hostname",COPY_URL:"Copy URL",MOVE_TO_FOLDER:"Move to Group",MOVE_TO_SUB_FOLDER:"Move to Sub-Group",DELETE_FOLDER:"Delete Group",RENAME_FOLDER:"Rename Group",
SHARE_FOLDER:"Share Folder",RENAME:"Rename",CREATE_SUB_FOLDER:"Create Sub-Group",OPEN_ALL:"Open All Sites",COPY_NOTE:"Copy Note",COPY_KEY:"Copy Key",FILL:"Fill",OPEN:"Open",SAVE:"Save",CANCEL:"Cancel",REVOKE:"Revoke Access",RESEND:"Resend Invitation",CANCEL_INVITE:"Cancel Invitation",REMOVE:"Remove",PURGE:"Purge",RESTORE:"Restore",CLOSE:"Close",MAXIMIZE:"Maximize",MINIMIZE:"Minimize",EDIT_ACCESS:"Edit Access",UNLINK_PERSONAL:"Unlink Personal Account",STOP_DOWNLOADING:"Stop Downloading Folder",START_DOWNLOADING:"Start Downloading Folder",
CONFIRM_REQUEST_ACCESS:"Confirm Request Access",VAULT_TOGGLE:"Toggle LastPass 3.0",AUTO_FILL:"Auto Fill",ADDED:"added",RENAMED:"renamed",SAVED:"saved",REMOVED:"removed",ACCEPTED:"accepted",DECLINED:"declined",PURGED:"purged",RESTORED:"restored",CLONE:"Clone",MORE_OPTIONS:"More Options",COPY:"Copy",EMPTY_COPY:"Nothing to copy",MANAGE:"Manage",MANAGE_FOLDER:"Manage Folder",CONVERT_FOLDER_TO_LEGACY:"Convert to Legacy Shared Folder",REQUEST_ACCESS:"Request Access",SHARED_WITH:"Shared with",SHARED_BY:"Shared by",
PENDING_SHARE:"Pending share",LAST_USED:"Last used",WAITING_PERIOD:"Waiting period",ACCESS_PENDING:"Access pending until",ACCESS_GRANTED:"Access granted",ACCOUNT_LINKED:"Account linked",GO_TO_URL:"Go to URL",UNEXPECTED_ERROR:"An unexpected error has occurred",READ_ONLY:"Read-Only",EMERGENCY_ACCESS_RECIPIENT:"Emergency Access Recipient",UNLINK:"Unlink",GENERATED:"Generated",NOT_DOWNLOADED:"Not downloaded",LINKED:"Linked",OUTSIDE_ENT:"Outside Enterprise",NO_SHARING_KEYS:"No Sharing Keys",GENERATED_PREFIX:"Generated Password for",
PURGE_ALL:"Purge All",LINKED_PERSONAL_ACCOUNT:"Linked Personal Account",EMERGENCY_ACCESS:"Emergency Access",COLLAPSE_ALL:"Collapse All",EXPAND_ALL:"Expand All",COMPACT_VIEW:"Show Compact View",LARGE_VIEW:"Show Large View",SHOW_PASSWORD:"Show Password",HIDE_PASSWORD:"Hide Password",GENERATE_PASSWORD:"Generate Password",ERROR:"Error",YES:"Yes",NO:"No",OPEN_DASHBOARD:"Open Dashboard",UPGRADE_PREMIUM:"Upgrade to Premium",SHOW:"SHOW",HIDE:"HIDE",NONE_GROUP:"(none)",NO_FOLDER:"No folder",ADD_ITEM:"Add Item",
NEVER:"Never",JUST_NOW:"Just now",SECOND:"A second ago",SECONDS:"%1 seconds ago",MINUTE:"A minute ago",MINUTES:"%1 minutes ago",HOUR:"An hour ago",HOURS:"%1 hours ago",DAY:"A day ago",DAYS:"%1 days ago",WEEK:"A week ago",WEEKS:"%1 weeks ago",MONTH:"A month ago",MONTHS:"%1 months ago",YEAR:"A year ago",YEARS:"%1 years ago",SITE:"Site",APPLICATION:"Application:",GROUP:"Group:",SECURE_NOTE:"Secure Note",FORM_FILL:"Form Fill",IDENTITY:"Identity",USER:"User",USER_GROUP:"User Group",SHARED_FOLDER:"Shared Folder",
ADD_FOLDER:"Add New Folder",SHARE_ITEMS:"Share Item",ADD_FORM_FILL:"Add Form Fill",ADD_NOTE:"Add Secure Note",ADD_SITE:"Add Site",ADD_SHARED_FOLDER:"Add Shared Folder",ADD_IDENTITY:"Add Identity",GIVE_EMER_ACCESS:"Give Emergency Access",ADD_CREDIT_MON:"Enable Credit Monitoring",DUUMY_TERMINATING_ENTRY:""};e.VaultDynamic={CONFIRM_PURGE:"Are you sure you want to purge %1? It will be permanently deleted from LastPass.",CONFIRM_PURGE_PLURAL:"Are you sure you want to purge the selected items? It will be permanently deleted from LastPass.",
CONFIRM_PURGE_FOLDER:"Are you sure you want to purge this folder's items? It will be permanently deleted from LastPass.",CONFIRM_RESTORE:"Are you sure you want to restore %1 to your vault?",CONFIRM_RESTORE_PLURAL:"Are you sure you want to restore the selected items to your vault?",CONFIRM_RESTORE_FOLDER:"Are you sure you want to restore this folder's items to your vault?",DELETE_CONFIRM:"Are you sure you want to delete %1?",DELETE_CONFIRM_PLURAL:"Are you sure you want to delete the selected items?",
PERMISSION_ERROR_MOVE:"You do not have permission to move items to %1",PERMISSION_ERROR_DELETE:"You do not have permission to delete items from %1"};e.Consts={NONE_GROUP:"(none)"};e.translateString=function(a){"undefined"!==typeof bg?a=bg.StringUtils.translate.apply(bg.StringUtils,arguments):"undefined"!==typeof StringUtils&&(a=StringUtils.translate.apply(StringUtils,arguments));if(1<arguments.length){for(var b=[],d=1,e=arguments.length;d<e;++d){var c=arguments[d];if("object"===typeof c){var f=a.indexOf("%"+
d);b.push(document.createTextNode(a.substring(0,f)));b.push(LPTools.createElement(c.type,c.attributes,c.text));a=a.substring(f+2)}}if(0<b.length)return 0<a.length&&b.push(a),b}return a};e.translate=function(a,b){for(var d,h;a;){if(3===a.nodeType)a.textContent=this.translateString(a.textContent);else if(1===a.nodeType)if(b=a.getAttribute("placeholder"),null!==b&&a.setAttribute("placeholder",this.translateString(b)),b=a.getAttribute("title"),null!==b&&a.setAttribute("title",this.translateString(b)),
null!==a.getAttribute("compoundtranslation")){b=a;d="";h=[];for(var c=b.firstChild;c;)3===c.nodeType?d+=c.textContent:1===c.nodeType&&(d+="%"+h.length+c.textContent+"%"+h.length,h.push(c)),c=c.nextSibling;d=e.translateString(d);LPTools.removeDOMChildren(b);c=d.indexOf("%");for(var f=null;-1<c;){var g=d.substring(0,c);null===f?(b.appendChild(document.createTextNode(g)),f=parseInt(d.charAt(c+1))):((f=h[f])?(f.textContent=g,b.appendChild(f)):b.appendChild(document.createTextNode(g)),f=null);d=d.substring(c+
2);c=d.indexOf("%")}0<d.length&&b.appendChild(document.createTextNode(d))}else e.translate(a.firstChild);a=a.nextSibling}};e.translateStrings=function(a){for(var b in a)a[b]=e.translateString(a[b])};return e})(Strings);"undefined"!==typeof module&&(module.exports=Strings);
//# sourceMappingURL=newvault_vaultStrings_js.js.map