(function(g){var h="",q=[],l={},r=["newvaultGlobal","dialog","buttons"],t=["dialog","dialogFields"],y=function(a){for(var b=0,c=q.length;b<c;++b)q[b]===a&&q.splice(b,1)},k=function(){var a=null,b=function(b,d){for(var c=0,e=b.length;c<e;++c){var p=b[c].getAttribute(d);p&&(a[p]=!0)}};return{loadFile:function(b,d){null===a&&k.initialize();var c=h+LPPlatform.getResourcePath(b.name);void 0===a[c]?(a[c]=!0,l[c]=[d],b.load(function(){var a=l[c];delete l[c];for(var b=0,d=a.length;b<d;++b)a[b]()})):l[c]?
l[c].push(d):d()},initialize:function(){null===a&&(a={},b(g.getElementsByTagName("link"),"href"),b(g.getElementsByTagName("script"),"src"))}}}(),e=function(){this.files=[];this.addedFiles={}};e.prototype.load=function(a){var b=0,c=this.files,d=function(){++b;b===c.length?a&&a():k.loadFile(c[b],d)};0===b&&0<c.length&&k.loadFile(c[0],d)};e.prototype.addFile=function(a){void 0===this.addedFiles[a.name]&&(this.files.push(a),this.addedFiles[a.name]=!0)};e.prototype.addFiles=function(a){if(a){a=[].concat(a);
for(var b=0,c=a.length;b<c;++b)this.addFile(a[b])}};var v=function(a){a.indexOf(".js")!==a.length-3&&(a=a+=".js");this.name=a;this.load=function(b){var c=g.createElement("script");c.setAttribute("type","text/javascript");c.setAttribute("src",h+LPPlatform.getResourcePath(a));LPPlatform.addEventListener(c,"load",b);g.body.appendChild(c)}},z=function(a){a.indexOf(".css")!==a.length-4&&(a=a+=".css");this.name=a;this.load=function(b){var c=g.createElement("link");c.setAttribute("type","text/css");c.setAttribute("rel",
"stylesheet");c.setAttribute("href",h+LPPlatform.getResourcePath(a));LPPlatform.addEventListener(c,"load",b);g.body.appendChild(c)}},m=function(a){e.call(this);a=a?r.concat(a):r;for(var b=0,c=a.length;b<c;++b)this.addFile(a[b])};m.prototype=Object.create(e.prototype);m.prototype.constructor=m;m.prototype.addFile=function(a){a&&e.prototype.addFile.call(this,new z(a))};m.prototype.load=function(a){for(var b=0,c=this.files,d=function(){++b===c.length&&a()},e=0,h=c.length;e<h;++e)k.loadFile(c[e],d)};
var n=function(a){e.call(this);a=a?t.concat(a):t;for(var b=0,c=a.length;b<c;++b)this.addFile(a[b])};n.prototype=Object.create(e.prototype);n.prototype.constructor=n;n.prototype.addFile=function(a){a&&e.prototype.addFile.call(this,new v(a))};LPRequire={requireJS:function(a,b){(new n(a)).load(b)}};LPDialog={DialogLoader:function(a){var b=this,c=!1,d=null,e=new n(a.js),g=new m(a.css),p=null;this.parentElementID=a.parentElementID;this.type=a.type;this.htmlSource=a.htmlSource;var l=function(){if(null===
p)for(var a in dialogs)if(dialogs[a]===b){p=a;break}return p},k=function(a,b){var c,f={},d=a?[].concat(a):[];b=b?[].concat(b):[];a=0;for(c=d.length;a<c;++a)f[d[a]]=!0;a=0;for(c=b.length;a<c;++a)f.hasOwnProperty(b[a])||d.push(b[a]);return d};this.extend=function(b){return new LPDialog.DialogLoader({id:b.id||a.id,htmlSource:k(a.htmlSource,b.htmlSource),css:k(a.css,b.css),js:k(a.js,b.js),type:b.type||a.type,parentElementID:b.parentElementID||a.parentElementID})};this.loadedJS=function(){return c};this.getID=
function(){return a.id};var r=function(b){return function(f){d=new window[a.type](b);c=!0;f(d)}}(this);this.loadJS=function(a){e?(Topics.get(Topics.DIALOG_LOADING).publish(),e.load(function(){r(a)})):r(a)};var t=function(a,b,c){c=c||0;var d=a.find("img");if(0<d.length){a=function(){var a=0,f=null,u=!1;0<c&&(f=setTimeout(function(){u=!0;a<d.length&&b()},c));return function(){++a;u||a!==d.length||(clearTimeout(f),f=null,b())}}();for(var f=0,u=d.length;f<u;++f)$(d[f]).bind("load",a)}else b()},v=function(a,
b){b=$(b);b.find("[dialogsection]").addBack("[dialogsection]").each(function(){var b=this.getAttribute("dialogsection");b=a.find("[dialogsection="+b+"]");b.before(this);b.remove()});b.find("[dialogsectionbefore]").addBack("[dialogsectionbefore]").each(function(){var b=this.getAttribute("dialogsectionbefore");a.find("[dialogsection="+b+"]").before(this)});b.find("[dialogsectionafter]").addBack("[dialogsectionafter]").each(function(){var b=this.getAttribute("dialogsectionafter");a.find("[dialogsection="+
b+"]").after(this)});b.find("[dialogsectionappend]").addBack("[dialogsectionappend]").each(function(){var b=this.getAttribute("dialogsectionappend");a.find("[dialogsection="+b+"]").append(this)});b.find("[dialogsectionprepend]").addBack("[dialogsectionprepend]").each(function(){var b=this.getAttribute("dialogsectionprepend");a.find("[dialogsection="+b+"]").prepend(this)})},w=function(b,c,d,e){d<c.length?LPPlatform.getHTML(h+a.htmlSource[d],function(a){v(b,a);w(b,c,++d,e)}):e()},x=function(b,c){var d=
function(){t(b,c,7500)};a.htmlSource instanceof Array?LPPlatform.getHTML(h+a.htmlSource[0],function(c){b.html(c);w(b,a.htmlSource,1,d)}):a.htmlSource?LPPlatform.getHTML(h+a.htmlSource,function(a){b.html(a);d()}):d()};this.load=function(a,b){g?g.load(function(){x(a,b)}):x(a,b)};this.open=function(){var a=arguments;a&&a[0]?a[0].type=this.type:a=[{type:this.type}];this.loadedJS()?d.open.apply(d,a):(q.push(b),this.loadJS(function(){LPDialog.beforeLoad?LPDialog.beforeLoad(l(),function(){d.open.apply(d,
a)}):d.open.apply(d,a);y(b)}))};this.close=function(){d&&d.close.apply(d,arguments)};this.getDialog=function(){return d}},JSFileSet:n,CSSFileSet:m,getPendingCount:function(){return q.length},getDialogs:function(){var a=[],b;for(b in dialogs)a.push(dialogs[b]);return a},setBaseURL:function(a){h=a},openDialog:function(a,b){dialogs[a].open(b)}}})("undefined"!==typeof document&&document);
dialogs={site:new LPDialog.DialogLoader({id:"siteDialog",htmlSource:"siteDialog.html",css:["buttons","dialog","siteDialog","passwordMeter"],js:"selectDropdown typeaheadDropdown dialog dialogWithGroupInput editableFieldsDialog siteDialog passwordMeter bloodhound bloodhoundDropdown".split(" "),type:"SiteDialog"}),note:new LPDialog.DialogLoader({id:"noteDialog",htmlSource:"noteDialog.html",css:["buttons","dialog","noteDialog"],js:"selectDropdown typeaheadDropdown stateDropdown phoneInput cc3l dialog dialogWithGroupInput noteDialog countrySelect timezoneSelect".split(" "),
type:"NoteDialog"}),customNoteTemplate:new LPDialog.DialogLoader({id:"customNoteTemplateDialog",htmlSource:"customNoteTemplateDialog.html",css:["buttons","dialog","customNoteTemplateDialog"],js:["selectDropdown","typeaheadDropdown","dialog","customNoteTemplateDialog"],type:"CustomNoteTemplateDialog"}),formFill:new LPDialog.DialogLoader({id:"formFillDialog",htmlSource:"formFillDialog.html",css:["buttons","dialog","formFillDialog"],js:"selectDropdown typeaheadDropdown formFillDialog countrySelect timezoneSelect stateDropdown phoneInput cc3l".split(" "),
type:"FormFillDialog"}),acceptShare:new LPDialog.DialogLoader({id:"acceptShareDialog",htmlSource:"acceptRejectShareDialog.html",css:["buttons","dialog","acceptRejectShareDialog"],js:["selectDropdown","typeaheadDropdown","dialog","dialogWithGroupInput","acceptRejectShareDialog"],type:"AcceptShareDialog"}),share:new LPDialog.DialogLoader({id:"shareDialog",htmlSource:"shareDialog.html",css:["buttons","dialog","shareDialog","containerSelectionDialog","vaultItem"],js:"selectDropdown typeaheadDropdown dialog shareDialog bloodhound bloodhoundDropdown vaultItemTypeahead sharingModel".split(" "),
type:"ShareDialog"}),identity:new LPDialog.DialogLoader({id:"identityDialog",htmlSource:"identityDialog.html",css:["buttons","dialog","containerSelectionDialog","identityDialog"],js:["dialog","containerSelectionDialog","identityDialog"],type:"IdentityDialog"}),sharedfolderAccess:new LPDialog.DialogLoader({id:"sharedFolderAccessDialog",htmlSource:"sharedFolderAccessDialog.html",css:["buttons","dialog","containerSelectionDialog","sharedFolderAccessDialog"],js:["dialog","containerSelectionDialog","sharedFolderAccessDialog"],
type:"SharedFolderAccessDialog"}),sharedFolder:new LPDialog.DialogLoader({id:"sharedFolderDialog",htmlSource:"sharedFolderDialog.html",css:["buttons","dialog","sharedFolderDialog"],js:"dialog sharedFolderDialog bloodhound selectDropdown typeaheadDropdown bloodhoundDropdown".split(" "),type:"SharedFolderDialog"}),familiesSharedFolder:new LPDialog.DialogLoader({id:"familiesSharedFolderDialog",htmlSource:"familiesSharedFolderDialog.html",css:["buttons","dialog","familiesSharedFolderDialog"],js:["dialog",
"selectDropdown","familiesSharedFolderDialog"],type:"FamiliesSharedFolderDialog"}),createSharedFolder:new LPDialog.DialogLoader({id:"createSharedFolderDialog",htmlSource:"createSharedFolderDialog.html",css:["buttons","dialog"],js:["dialog","dialogWithGroupInput","folderDialog"],type:"CreateSharedFolderDialog"}),convertLegacySharedFolder:new LPDialog.DialogLoader({id:"convertLegacySharedFolderDialog",htmlSource:"convertLegacySharedFolderDialog.html",css:["buttons","dialog","convertLegacySharedFolderDialog"],
js:["dialog","selectDropdown","convertLegacySharedFolderDialog"],type:"ConvertLegacySharedFolderDialog"}),createCreditMonitoring:new LPDialog.DialogLoader({id:"createCreditMonitoringDialog",htmlSource:"createCreditMonitoringDialog.html",css:["buttons","dialog","createCreditMonitoringDialog"],js:["dialog","createCreditMonitoringDialog"],type:"CreateCreditMonitoringDialog"}),generatePassword:new LPDialog.DialogLoader({id:"generatePasswordDialog",htmlSource:"generatePasswordDialog.html",css:["buttons",
"dialog","generatePasswordDialog","passwordMeter"],js:["dialog","generatePasswordDialog","selectDropdown","passwordMeter"],type:"GeneratePasswordDialog"}),betterGeneratePassword:new LPDialog.DialogLoader({id:"betterGeneratePasswordDialog",htmlSource:"betterGeneratePasswordDialog.html",css:["buttons","dialog","passwordMeter","betterGeneratePassword","betterGeneratePasswordDialog"],js:["dialog","betterGeneratePasswordDialog","selectDropdown","passwordMeter"],type:"BetterGeneratePasswordDialog"}),login:new LPDialog.DialogLoader({id:"loginDialog",
htmlSource:"loginDialog.html",css:["loginDialog"],js:["loginDialog","capslockstate"],type:"LoginDialog"}),reprompt:new LPDialog.DialogLoader({id:"repromptDialog",htmlSource:"repromptDialog.html",css:["repromptDialog"],js:["repromptDialog"],type:"RepromptDialog"}),createAccount:new LPDialog.DialogLoader({id:"createAccountDialog",htmlSource:"createAccountDialog.html",css:["buttons","dialog","createAccountDialog","passwordMeter"],js:["dialog","createAccountDialog","selectDropdown","passwordMeter"],type:"CreateAccountDialog"}),
folder:new LPDialog.DialogLoader({id:"folderDialog",type:"FolderDialog",css:["buttons","dialog"],js:["dialog","selectDropdown","typeaheadDropdown","dialogWithGroupInput","folderDialog"],htmlSource:"folderDialog.html"}),fieldHistory:new LPDialog.DialogLoader({id:"fieldHistoryDialog",htmlSource:"fieldHistoryDialog.html",css:["buttons","dialog","fieldHistoryDialog"],js:["dialog","fieldHistoryDialog"],type:"FieldHistoryDialog"}),confirmation:new LPDialog.DialogLoader({id:"confirmationDialog",htmlSource:"confirmationDialog.html",
css:["buttons","dialog"],js:["dialog","confirmationDialog"],type:"ConfirmationDialog"}),alert:new LPDialog.DialogLoader({id:"alertDialog",htmlSource:"alertDialog.html",css:["buttons","dialog"],js:["dialog","confirmationDialog"],type:"AlertDialog"}),enterpriseTrial:new LPDialog.DialogLoader({id:"enterpriseTrialDialog",htmlSource:"enterpriseTrialDialog.html",css:["buttons","dialog"],js:["dialog","enterpriseTrialDialog"],type:"EnterpriseTrialDialog"}),denyEmergencyAccess:new LPDialog.DialogLoader({id:"denyEmergencyAccessDialog",
htmlSource:"denyEmergencyAccessDialog.html",css:["buttons","dialog"],js:["dialog","denyEmergencyAccessDialog"],type:"DenyEmergencyAccessDialog"}),verifyEmail:new LPDialog.DialogLoader({id:"verifyEmailDialog",htmlSource:"verifyEmailDialog.html",css:["buttons","dialog"],js:["dialog","verifyEmailDialog"],type:"VerifyEmailDialog"}),application:new LPDialog.DialogLoader({id:"applicationDialog",htmlSource:"applicationDialog.html",css:["buttons","dialog","passwordMeter"],js:"dialog dialogWithGroupInput editableFieldsDialog passwordMeter applicationDialog selectDropdown typeaheadDropdown".split(" "),
type:"ApplicationDialog"}),chooseProfile:new LPDialog.DialogLoader({id:"chooseProfileDialog",htmlSource:"chooseProfileDialog.html",css:["buttons","dialog","chooseProfileDialog"],js:["dialog","chooseProfileDialog"],type:"ChooseProfileDialog"}),vaultItemSelect:new LPDialog.DialogLoader({id:"vaultItemSelectDialog",htmlSource:"vaultItemSelectDialog.html",css:["buttons","dialog","vaultItem"],js:["dialog","vaultItemSelectDialog"],type:"VaultItemSelectDialog"}),inviteFriends:new LPDialog.DialogLoader({id:"inviteFriendsDialog",
htmlSource:"inviteFriendsDialog.html",css:["buttons","dialog"],js:["dialog","inviteFriendsDialog"],type:"InviteFriendsDialog"}),addEmergencyAccess:new LPDialog.DialogLoader({id:"addEmergencyAccessDialog",htmlSource:"addEmergencyAccessDialog.html",css:["buttons","dialog"],js:["dialog","addEmergencyAccessDialog"],type:"AddEmergencyAccessDialog"}),upgradePremium:new LPDialog.DialogLoader({id:"upgradePremiumDialog",htmlSource:"upgradePremiumDialog.html",css:["buttons","dialog"],js:["dialog","upgradePremiumDialog"],
type:"UpgradePremiumDialog"}),upgradeFamiliesForFolderSharing:new LPDialog.DialogLoader({id:"upgradeFamiliesForFolderSharingDialog",htmlSource:"upgradeFamiliesForFolderSharingDialog.html",css:["buttons","dialog"],js:["dialog","upgradeFamiliesForFolderSharingDialog"],type:"UpgradeFamiliesForFolderSharingDialog"}),familiesInvitation:new LPDialog.DialogLoader({id:"familiesInvitationDialog",htmlSource:"familiesInvitationDialog.html",css:["buttons","dialog"],js:["dialog","familiesInvitationDialog"],type:"FamiliesInvitationDialog"}),
tryFamilies:new LPDialog.DialogLoader({id:"tryFamiliesDialog",htmlSource:"tryFamiliesDialog.html",css:["buttons","dialog"],js:["dialog","tryFamiliesDialog"],type:"TryFamiliesDialog"}),sharingKey:new LPDialog.DialogLoader({id:"sharingKeyDialog",htmlSource:"sharingKeyDialog.html",css:["buttons","dialog"],js:["dialog","sharingKeyDialog"],type:"SharingKeyDialog"}),addFormField:new LPDialog.DialogLoader({id:"addFormFieldDialog",htmlSource:"addFormFieldDialog.html",js:["dialog","dialogWithGroupInput","editableFieldsDialog"],
type:"AddFormFieldDialog"}),addItem:new LPDialog.DialogLoader({id:"addItemDialog",htmlSource:"addItemDialog.html",js:["addItemDialog"],css:["addItemDialog","lpGrid"],type:"AddItemDialog"}),restrictedSharing:new LPDialog.DialogLoader({id:"restrictedSharingDialog",htmlSource:"restrictedSharingDialog.html",js:["restrictedSharingDialog"],css:["buttons","restrictedSharingDialog"],type:"RestrictedSharingDialog"}),restrictedEmergencyAccess:new LPDialog.DialogLoader({id:"restrictedEmergencyAccess",htmlSource:"restrictedEmergencyAccessDialog.html",
js:["restrictedEmergencyAccessDialog"],css:["dialog","buttons","restrictedEmergencyAccessDialog"],type:"RestrictedEmergencyAccessDialog"}),tourDialogBase:new LPDialog.DialogLoader({id:"introTourDialog",htmlSource:"Tour/introTourDialog.html",css:["buttons","dialog","lpGrid","Tour/introTourDialog"],js:"dialog lpArrow lpPing lpTag Tour/introTourData Tour/introTourFlow Tour/introTourQueue Tour/introTour Tour/introTourDialog".split(" "),type:"IntroTourDialog"}),vaultInfoBanner:new LPDialog.DialogLoader({css:["buttons",
"dialog","lpGrid","vaultInfoBanner"],htmlSource:"vaultInfoBanner.html",js:["dialog","vaultInfoBanner"],type:"VaultInfoBanner"}),vaultTierExpiredDialog:new LPDialog.DialogLoader({id:"vaultTierExpiredDialog",htmlSource:"vaultTierExpiredDialog.html",css:["buttons","dialog"],js:["dialog","vaultTierExpiredDialog"],type:"TierExpiredDialog"})};dialogs.changePassword=dialogs.vaultItemSelect.extend({id:"changePasswordDialog",js:"changePasswordDialog",type:"ChangePasswordDialog"});
"undefined"!==typeof module&&(module.exports=dialogs);
//# sourceMappingURL=newvault_dialogs_js.js.map