var VaultInfoBanner=function(f,q,l,g){function p(c){var a=b.prototype._options.dimensions,d=f("#options"),e=f("#tools"),k=f("#sharingMenu"),h=f("#emergencyAccessMenu");c?(d.removeAttr("style"),h.removeAttr("style"),e.removeAttr("style"),k.removeAttr("style"),f("#main").removeAttr("style")):(d.is(":visible")&&(d.css("top",a.dialogPosition.top+a.dialogDimensions.height),f("#main").css("top",d.innerHeight()+d.offset().top+"px")),k.is(":visible")&&(k.css("top",a.dialogPosition.top+a.dialogDimensions.height),
d.css("top",k.innerHeight()+k.offset().top+"px"),f("#main").css("top",d.innerHeight()+d.offset().top+"px")),e.is(":visible")&&(e.css("top",a.dialogPosition.top+a.dialogDimensions.height),f("#main").css("top",e.innerHeight()+e.offset().top+"px")),h.is(":visible")&&(h.css("top",a.dialogPosition.top+a.dialogDimensions.height),f("#main").css("top",h.innerHeight()+h.offset().top+"px")))}function m(b,a,d,e,f){var c=0;switch(b){case "top":case "left":c=a?d:d+e;break;case "right":case "bottom":c=a?d+e-f:
d-f}return c}function n(b,a,d,e,f){switch(b){case "top":case "left":b=a;break;case "right":case "bottom":b=a+d-f;break;default:b=e-Math.round(f/2)}return b}var b=function(c){l.call(this,c,{maximizeButtonEnabled:!1,dynamicHeight:!0,hideHeader:!0,hideButtons:!0,confirmOnClose:!1,buttonsInsideContent:!0,isModal:!1});b.prototype._options={}};b.prototype=Object.create(l.prototype);b.prototype.createButton=function(b,a,d,e){if(b&&a){var c=a.style||"",h=a.sizeStyle||"col-6",g=a.autoId||"";a=f("<div></div>").addClass(h+
" infoBtn").append(f("<button></button>").text(a.text).data("index",d).addClass("btn-base radius-sm "+c).attr("automation-id",g).off().on("click",e));b.append(a)}};b.prototype.setup=function(c,a){l.prototype.setup.apply(this,arguments);if(a){var d=this;b.prototype.$element=this.$element;b.prototype._options=a?a:{};b.prototype.sendSegmentEvent("show");b.prototype.$element.removeClass().addClass("dialog responsive vault-info-banner");b.prototype._options.dialogClass&&b.prototype.$element.addClass(b.prototype._options.dialogClass);
b.prototype.setText(b.prototype._options.title,b.prototype.$element.find("#mainTitle"));var e="function"===typeof b.prototype._options.contentText1?b.prototype._options.contentText1():b.prototype._options.contentText1;b.prototype.setText(e,b.prototype.$element.find("#contentText1"));e="function"===typeof b.prototype._options.contentText2?b.prototype._options.contentText2():b.prototype._options.contentText2;b.prototype.setText(e,b.prototype.$element.find("#contentText2"));e=c.find("#btnClose");if(b.prototype._options.hideXCloseBtn)e.hide();
else e.off().on("click",function(a){b.prototype._options.closeHandler&&"function"===typeof b.prototype._options.closeHandler&&b.prototype._options.closeHandler();b.prototype.sendSegmentEvent("close");d.close(!0)});e=d.$element.find(".buttons");f(".infoBtn").remove();"banner"===b.prototype._options.dialogClass&&(e=d.$element.find(".mainTitle"));b.prototype._options.buttons=b.prototype._options.buttons?b.prototype._options.buttons:[];for(var g=0;g<b.prototype._options.buttons.length;g++)b.prototype.createButton(e,
b.prototype._options.buttons[g],g,function(a){a.preventDefault();a=f(a.target).data("index");f.isNumeric(a)&&0<=a&&a<b.prototype._options.buttons.length&&(a=b.prototype._options.buttons[a],"undefined"!==typeof a.segment&&b.prototype.sendSegmentEvent(a.segment),a.action&&"function"===typeof a.action&&a.action(),a.closeOnClick&&d.close(!0))});b.prototype._options.dimensions={targetId:"#header",align:"left",orientation:"top",fillWidth:"#main"};f("#vault").addClass("vault-info-overrides");b.prototype.setSize(b.prototype.$element,
b.prototype._options.dimensions);b.prototype.setPosition(b.prototype.$element,b.prototype._options.dimensions);b.prototype.subscribeToWindowResize()}};b.prototype.setText=function(b,a){b&&a?a.text(b).show():a.hide()};b.prototype.setPosition=function(c,a){a.dialogPosition=null;a&&a.targetId&&(a.$targetEl=f(a.targetId),a.targetDimensions=b.prototype.getDimensions(a.$targetEl),a.dialogPosition=b.prototype.computeDialogPosition(c,a));a.dialogPosition&&c.offset(a.dialogPosition);p()};b.prototype.setSize=
function(c,a){if(a){a.$targetEl=f(a.targetId);var d=b.prototype.getDimensions(a.$targetEl),e;a.fillWidth?(e=f(a.fillWidth))&&0<e.length?c.width(e.width()):c.width(d.width):c.css("width","");a.fillHeight?(e=f(a.fillHeight))&&0<e.length?c.height(e.height()):c.height(d.height):c.css("height","")}};b.prototype.subscribeToWindowResize=function(){b.prototype.positionAndResizeHandler=function(){b.prototype.setPosition(b.prototype.$element,b.prototype._options.dimensions);b.prototype.setSize(b.prototype.$element,
b.prototype._options.dimensions)};window&&window.addEventListener("resize",b.prototype.positionAndResizeHandler);g.get(g.VAULT_LEFT_MENU_TOGGLE).subscribe(b.prototype.positionAndResizeHandler);g.get(g.EMPTY_VAULT_STATE_CHANGE).subscribe(b.prototype.positionAndResizeHandler)};b.prototype.unSubscribeToWindowResize=function(){"function"===typeof b.prototype.positionAndResizeHandler&&(g.get(g.VAULT_LEFT_MENU_TOGGLE).unsubscribe(b.prototype.positionAndResizeHandler),g.get(g.EMPTY_VAULT_STATE_CHANGE).unsubscribe(b.prototype.positionAndResizeHandler),
window&&(window.removeEventListener&&window.removeEventListener("resize",b.prototype.positionAndResizeHandler),b.prototype.positionAndResizeHandler=null))};b.prototype.computeDialogPosition=function(c,a){if(c&&0<c.length&&a&&0<a.$targetEl.length){a.dialogDimensions=b.prototype.getDimensions(c);c={top:0,left:0};var d=a.align||"center";switch(a.orientation){case "top":c.left=n(d,a.targetDimensions.left,a.targetDimensions.width,a.targetDimensions.center.left,a.dialogDimensions.width);c.top=m(a.orientation,
a.inside,a.targetDimensions.top,a.targetDimensions.height,a.dialogDimensions.height);break;case "bottom":c.left=n(d,a.targetDimensions.left,a.targetDimensions.width,a.targetDimensions.center.left,a.dialogDimensions.width);c.top=m(a.orientation,a.inside,a.targetDimensions.top,a.targetDimensions.height,a.dialogDimensions.height);break;case "left":c.top=n(d,a.targetDimensions.top,a.targetDimensions.height,a.targetDimensions.center.top,a.dialogDimensions.height);c.left=m(a.orientation,a.inside,a.targetDimensions.left,
a.targetDimensions.width,a.dialogDimensions.width);break;case "right":c.top=n(d,a.targetDimensions.top,a.targetDimensions.height,a.targetDimensions.center.top,a.dialogDimensions.height),c.left=m(a.orientation,a.inside,a.targetDimensions.left,a.targetDimensions.width,a.dialogDimensions.width)}a.offset&&(c.top+=a.offset.top,c.left+=a.offset.left);return c}return null};b.prototype.getDimensions=function(b){return b&&0<b.length?(b=f.extend({height:b.height(),width:b.width()},b.offset()),b.center={top:Math.round(b.top+
b.height/2),left:Math.round(b.left+b.width/2)},b):f.extend({height:0,width:0},{top:0,left:0,center:{top:0,left:0}})};b.prototype.close=function(c){c&&(p(!0),f("#vault").removeClass("vault-info-overrides"),l.prototype.close.apply(this,arguments),b.prototype.unSubscribeToWindowResize())};b.prototype.getZIndex=function(){var c=b.prototype.$element?b.prototype.$element.css("z-index"):"auto";if("auto"===c)return 0;c=parseInt(c);return 8>c?8:c};b.prototype.sendSegmentEvent=function(c){if("undefined"!==
typeof b.prototype._options.segmentEvents&&"undefined"!==typeof b.prototype._options.segmentEvents[c]){var a={};"undefined"!==typeof b.prototype._options.segmentEvents[c].properties&&(a=b.prototype._options.segmentEvents[c].properties);bg.sendLpImprove(b.prototype._options.segmentEvents[c].name,a)}else console.log(c+" is not a defined segment event")};return b}(jQuery,Strings,Dialog,Topics);
//# sourceMappingURL=newvault_vaultInfoBanner_js.js.map