User=function(g,e,c,b){this._username=g;this._accountClass=e;this._roleName=b;this._userMenuText=this._element=null;this._identities=c;this._identityDropdown=null;(function(a){a.identityEnableCallback=function(b){a._identityDropdown&&a._identityDropdown.setValue(b._data.deciname,!1);a._userMenuText&&a._userMenuText.children().detach();if(b instanceof AllIdentity)a._userMenuText.append(a._userInfo);else{var c=LPTools.createElement("ul","userMenuText");c.appendChild(LPTools.createElement("li","userMenuTextSingle truncateShort",
b.getName()));a._userMenuText.append(c)}};a.identityAddedCallback=function(b){a._identities.push(b);a._identityDropdown?a._identityDropdown.setIdentities(a._identities):a.initializeIdentityDropdown(a._element.get(0).firstChild)};Topics.get(Topics.IDENTITY_ENABLE).subscribe(a.identityEnableCallback);Topics.get(Topics.IDENTITY_ADDED).subscribe(a.identityAddedCallback)})(this)};
(function(g){User.prototype.destruct=function(){this._element.unbind();this._element.empty();this._userMenuText.empty();Topics.get(Topics.IDENTITY_ENABLE).unsubscribe(this.identityEnableCallback);Topics.get(Topics.IDENTITY_ADDED).unsubscribe(this.identityAddedCallback);this._identityDropdown=this._identities=this._userMenuText=this._element=this._roleName=this._accountClass=this._username=null};var e=function(c,b,a,d,f){f=f||{};f.id=a;f["class"]="menuListItem";a=LPTools.createElement("li");b=LPTools.createElement(b,
f);b.textContent=d;a.appendChild(b);c.appendChild(a);return a};User.prototype.initializeIdentityDropdown=function(c){var b=LPTools.createElement("li","menuListHeader identityDropdownMenuItem");b.appendChild(LPTools.createElement("div",{id:"identityDropdownContainer"}));b.children[0].appendChild(LPTools.createElement("img",{id:"identityDropdownIcon",src:"images/vault_4.0/Identity_Avatar.png"}));var a=LPTools.createElement("div");b.children[0].appendChild(a);var d=LPTools.createElement("input",{id:"identityDropdown",
"class":"dialogInput selectDropdown",type:"text"});a.appendChild(d);c.insertBefore(b,c.firstChild);this._identityDropdown=new IdentityDropdown(d,this._identities);c=0;for(a=this._identities.length;c<a;++c)d=this._identities[c],d._enabled&&this._identityDropdown.setValue(d.getName(),!1);LPPlatform.addEventListener(b,"click",function(a){a.stopPropagation()});$(b.nextElementSibling).addClass("divider")};User.prototype.initialize=function(c,b){c.empty();var a=LPTools.createElement("ul"),d="";this._userInfo=
LPTools.createElement("ul","userMenuText");this._userInfo.appendChild(LPTools.createElement("li","userMenuTextPrimary truncateShort",this._username));d=this._accountClass===Constants.USER_ENTERPRISE_ROLE?LPProxy.isIdentity()?Strings.translateString("Identity %0 User",this._roleName):Strings.translateString("Enterprise %0 User",this._roleName):LPProxy.isFamilyUser()?LPProxy.isAdmin()?Strings.translateString("Family manager"):Strings.translateString("Family member"):LPProxy.isIdentity()?LPProxy.isAdmin()?
Strings.translateString("Identity Admin"):Strings.translateString("Identity User"):Strings.translateString(this._accountClass);this._userInfo.appendChild(LPTools.createElement("li","userMenuTextSecondary",d));b.append(this._userInfo);$(e(a,"div","accountSettingsIcon",Strings.Vault.ACCOUNT_SETTINGS)).bind("click",function(){Topics.get(Topics.EDIT_SETTINGS).publish({source:"accountdropdown"})});$(e(a,"a","helpCenterIcon",Strings.Vault.HELP_CENTER,{href:"https://support.logmeininc.com/lastpass",target:"_blank"})).bind("click",
function(){window.open("https://support.logmeininc.com/lastpass")});$(e(a,"a","attendWebinarIcon",Strings.Vault.ATTEND_WEBINAR,{href:"https://register.gotowebinar.com/rt/8722554781298103307?source=s",target:"_blank"})).bind("click",function(){window.open("https://register.gotowebinar.com/rt/8722554781298103307?source=s")});$(e(a,"div","logoutIcon",Strings.Vault.LOGOUT)).bind("click",function(){bg.sendLpImprove("logout_clicked",{source:"vault"});LPProxy.logout()});c.append(a);1<this._identities.length&&
this.initializeIdentityDropdown(a);this._element=c;this._userMenuText=b};User.prototype.isFreeOrTrial=function(){return this._accountClass===Constants.USER_FREE||this._accountClass===Constants.USER_PREMIUM_TRIAL};User.prototype.isFree=function(){return this._accountClass===Constants.USER_FREE}})(document);
//# sourceMappingURL=newvault_vaultModel_js.js.map